bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/include/bp_be_mmu_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_checker/bp_be_checker_top.v, bp_be/src/v/bp_be_checker/bp_be_detector.v, bp_be/src/v/bp_be_checker/bp_be_director.v, bp_be/src/v/bp_be_mmu/bp_be_mmu_top.v, bp_be/src/v/bp_be_top.v, bp_be/test/tb/bp_be_trace_demo/Makefile.frag
Original: Critical paths through npc_check, then through nop logic, then cache->cache path which was unnecessary because of cache miss poison logic.
Frequency: 400 MHz
Area: 1283284.900015
Median
IPC: 466
MIPS: 186.4 
Power: 1.1842e+05 uW
EPI: 635.3 pJ
Multiply
IPC: 488
MIPS: 195.2
Power: 1.1769e+05 uW
EPI: 602.9 pJ
Towers
IPC: 505
MIPS: 202
Power: 1.2628e+05 uW
EPI: 625.1 pJ
Vvadd:
IPC: 453
MIPS: 181.2
Power: 1.1553e+05 uW
 EPI: 637.6 pJ
———————————————
With fixes: critical path now through dcache->bypass paths->dispatch.  Additionally, a parameter (default off) is added to disable this load->use forwarding. Expect an IPC decrease if this parameter is enabled.
Frequency: 513 MHz
Area: 1287764.798082
Median
IPC: 454
Power: 1.1736e+05
MIPS: 232.9
EPI: 503.9
Multiply
IPC: 460
Power: …
=> PParrot BE critical path fixes

bp_fe/src/v/bp_fe_branch_predictor.v
Deleted the BHT and added static branch prediction based on the lowest five bits of the pc and the next pc from the btb. This assumes two things. One, forward branches are not taken and backward branches are taken. Two, code usually does not branch more than five to ten instructions away, so we could assume all of the high order bits are the same, and we only need to compare about the lowest five bits.
Instr/S:
--------
Baseline:         206.28 MInstr/S
Optimization: 211.40 MInstr/S
Change:          5.12 MInstr/S or 2.45% increase
J/Instr
--------
Baseline:         369.65 pJ/Instr
Optimization: 353.86 pJ/Instr
Change:          -15.79 pJ/Instr or 4.48% decrease
Area
--------
Baseline:         1333895 um^2
Optimization: 1330278 um^2
Change:          -3617 um^2 or 0.272% decrease
As you can …
=> PC_Gen static branch prediction

bp_fe/src/v/bp_fe_btb.v, bp_fe/src/v/bp_fe_pc_gen.v, bp_fe/test/common/mock/mock_be_trace.v
There was some complex logic in the pc gen module that meant that branch prediction wasn't working correctly. To remedy this, we made a couple modifications:
-Simplifying the pipelining within PC Gen by removing a register and prioritizing taking a redirect PC over icache miss PC. This is not strictly something we expect a PPA improvement from, but it makes it much easier to hook up a branch predictor.
-For now, the BHT/BTB are replaced with static prediction (forward not taken, backwards taken). 
We branched from the pparrot branch and compared PPA metrics post-synthesis:
Our minimum clock period is the same for both designs at 2.3 ns. The average instructions/s before optimization is 85,151,250 before optimization and 187,920,000 post optimization. **This is a 120% throughput …
=> Modifying PC gen logic for branch prediction

bp_me/src/v/cce/bp_cce_dir.v, bp_me/src/v/cce/bp_cce_top.v, bp_me/src/v/network/bp_coherence_network.v, bp_me/src/v/network/bp_coherence_network_channel.v, bp_me/syn/flist.vcs, bp_me/test/common/bp_mem.v
Added clock gating to:
- L2 and CCE Directory
- FIFOs in Network
- FIFOs between CCE and L2
(Uses clock_gating branch of EE 477 bsg_ip_cores.)
**Results:**
Baseline:
Post Synth |   |  
-- | -- | --
Power p(J/I) | Performance M(I/s) | Area (cell only) (mm^2)
2,861.28 | 61.8 | 2.470
This branch: _percentages below are in comparison to baseline_
Post Synth |   |  
-- | -- | --
Power p(J/I) | Performance M(I/s) | Area (cell only) (mm^2)
573.65 | 60.1 | 2.473
-79.95 | -2.67 | 0.13
(Post PnR results in progress)
**Conclusion:**
Power down 80% post synth with small losses to performance and area.
=> PPArrot: ME (Chase & Derek) Clock gating for network and large rams

bp_be/src/v/bp_be_mmu/bp_be_dcache/bp_be_dcache.v, bp_be/syn/flist.vcs
We tried to do clock gating on mems. The results show ~10% less in power.
clock speed: 351 Mhz -> 379 Mhz
area:1.316 mm^2 -> 1.311 mm^2
Power: 0.152 W->0.137 W
=> clk gating on mems

bp_be/src/v/bp_be_mmu/bp_be_dcache/bp_be_dcache.v, bp_be/syn/flist.vcs
We hardened stat_mem. The results show ~4% less in area and ~10% less in power.
clock speed: 351 Mhz -> 357.7 Mhz
area:1.316 mm^2 -> 1.268 mm^2
Power(towers_rom): 0.152 W->0.1382 W
=> backend- harden status memory

bp_be/src/v/bp_be_mmu/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mmu/bp_be_dcache/bp_be_dcache_lce.v
Added clkgating parameter in dcache.v and dcache_lce.v in bp_be_mmu.
The following data is collected at constraint = 3.0ns and uncertainty of 0.5ns
This branch is not built upon Dan's becriticalpathfixes branch. The power saving makes sense. However, I expect the area to increase by a bit in dcache due to the clock gating logic and no change in performance. Though dcache's area did increase, the calculator's and checker's area decreased (which I'm not 100% what happened just yet). Performance also improved, though only by a little.
=> Pparrot mittal tang dcache add param clkgate

bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_lce.v, bp_fe/syn/flist.vcs
We aimed to reduce power consumed in the icache section of the front end
From viewing initial power reports we noticed that in some test cases (such as towers) power consumed by the icache region was around 70% of total power in the front end. Some of the power contributions were suspicious, like how the LCE consummed over 35% of overall power in the front end. Specifically the two deep async fifos. What really surprised us is all the fifos from the lce (3 of them) used the same amount of power even though only one of them was used most of the time!
We clock gated these fifos and also the data mem, tag mem, and meta data mem (although these had low impact which makes sense since they are accessed almost all the time, minus during cache misses, and we made sure that their valid signals …
=> ICache clock gating - lce fifos and cache memory banks

bp_me/src/v/network/bp_coherence_network.v, bp_me/src/v/network/bp_coherence_network_channel.v, bp_me/src/v/network/bp_coherence_network_individual_input_serializer.v, bp_me/src/v/network/bp_coherence_network_individual_output_deserializer.v, bp_me/src/v/network/bp_coherence_network_input_serializer.v, bp_me/src/v/network/bp_coherence_network_output_deserializer.v
Serializer and deserializer modules were created. This reduces the width of the network but increases its latency.
Either the number of blocks into which the packets are divided or the width of the smaller blocks is configurable.
A FIFO can optionally be added before each serializer module, to prevent messages being dropped because of the added latency.
=> Reduction of network width by dividing the packets into smaller blocks using serializer and deserializer modules

bp_me/src/v/network/bp_coherence_network.v, bp_me/src/v/network/bp_coherence_network_channel.v, bp_me/src/v/network/bp_coherence_network_individual_input_serializer.v, bp_me/src/v/network/bp_coherence_network_individual_output_deserializer.v, bp_me/src/v/network/bp_coherence_network_input_serializer.v, bp_me/src/v/network/bp_coherence_network_output_deserializer.v
Each packet sent through the network contains the destination ID twice. The network width was reduced by removing this redundancy, modifying the RTL code.
This builds on our previous request.
=> Reduction of network redundance

bp_be/src/v/bp_be_calculator/bp_be_regfile.v
testbench | Power baseline post synth | Power SRAM post synth | Difference
-- | -- | -- | --
none | 1.2011e5 uW | 1.1333e5 uW | -5.64%
median | 1.1842e5 uW | 1.1202e5 uW | -5.40%
multiply | 1.1769e5 uW | 1.1172e5 uW | -5.07%
tower | 1.2628e5 uW | 1.1786e5 uW | -6.67%
vvadd | 1.1553e5 uW | 1.0902e5 uW | -5.63%
Total cell Area:
Baseline post synth:		1283284
Harden SRAM post synth:	1229303
Difference:			-4.2%
Performance:
Baseline post synth:		2.5 ns
Harden SRAM post synth:	2.5 - 0.06 ns = 2.44 ns
Difference:			-2.4%
Other file changes:
add mem cfg file in 
ee477-designs/toplevels/bsg_black_parrot_be/cfg/saed_90/saed90_64x32_1r1w_bit.cfg
add 64x32 macro option in this file
bsg_ip_cores/hard/saed_90/bsg_mem/bsg_mem_1r1w_sync.v
credit to Mingcun Fan
=> pparrot harden regfile

bp_be/src/v/bp_be_checker/bp_be_detector.v, bp_be/src/v/bp_be_mmu/bp_be_dcache/bp_be_dcache.v
Simplified the RTL in the detector and dcache module to reduce the number of lines in the code and to enhance the readability respectively. The post-synth PPA before and after the change is as follows (towers_rom):
Before:-
Performance: 404MHz
Power: 1.2599e+05uW
Area: 1283284.900015um^2
After:-
Performance: 411.5MHz
Power: 1.2605e+05uW
Area: 1282741.156035um^2
=> RTLchanges

bp_be/src/include/bp_be_ctl_defines.vh, bp_be/src/include/bp_be_dcache/bp_be_dcache_pkg.vh, bp_be/src/include/bp_be_dcache/bp_be_dcache_pkt.vh, bp_be/src/include/bp_be_rv64_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_checker/bp_be_scheduler.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_req.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_be/test/common/bp_be_nonsynth_tracer.v, bp_be/test/rom/Makefile.frag, bp_be/test/rom/src/demos/src/atomics.S, bp_be/test/rom/src/isa/rv64ui/lrsc.S
Working on adding LR/SC to the D$.  I was planning on using the riscv-test lrsc as initial validation, but it depends on a multiply instruction, which we don't currently emulate or implement. It does pass several of the test cases, but we can't verify the main, large one.   Of course, we're only running on 1 core, so we wouldn't run into very many interesting cases, anyway.
@tommydcjung 
1) Can you review these changes to D$ and make sure they look good?
2) Can you point me to all of the documents which will need updating with information about LR/SC?
3) Do you think it would be feasible to modify the axe test / uncached I/O test to spit out LR/SC and check them somehow? The emitting seems doable, but I'm not really sure how to do the verification
=> Adding LR/SC to D$

bp_be/test/common/bp_be_nonsynth_tracer.v
Small tweak in the back-end nonsynth tracer, so each core prints to a
separate debug log file
=> Modify logging to support multicore

bp_common/test/Makefile.frag, bp_common/test/src/demos/Makefile, bp_common/test/src/demos/Makefile.frag, bp_common/test/src/demos/src/atomic_queue_demo.c, bp_common/test/src/demos/src/bp_utils.c, bp_common/test/src/demos/src/bp_utils.h, bp_common/test/src/demos/src/exception.S, bp_common/test/src/demos/src/hello_world_atomic.c, bp_common/test/src/demos/src/reloc_queue_demo.c, bp_common/test/src/demos/src/start.S
Added a basic test (hello_world_atomic) where cores use amoadd to increment a shared counter and print out their ID. Also made a version of the queue demo (atomic_queue_demo) that uses amoswap to lock the shared queue. Both of these were tested up to 8 cores.
This PR also include modifications to the start code to properly support multicore as every core needs its own emulation stack as well as program stack. The trap vector code was also modified to save stack pointers appropriately to reflect this change
=> Upgrade demos with atomics

bp_me/src/v/cce/bp_cce_top.v
This change increase the amount of buffering at each CCE for LCE and MEM Response message networks. This buffering is required to prevent the CCE / system from potentially deadlocking due to these networks filling up. Messages on these networks are sunk by the CCE in a delayed manner (exactly when depends on what the CCE microcode is doing).
The CCE may be unable to immediately sink a memory response because it is processing another request. The maximum number of outstanding memory requests is capped at the number of way-groups managed by the CCE (enforced by the pending bit).
The CCE may be unable to immediately sink a transfer or coherence ack (LCE Responses) because it is processing another request. The maximum number of these acks that may be outstanding prior to the CCE entering a …
=> increase buffering for LCE and Mem Response messages

bp_me/src/v/cce/bp_cce_msg.v
This change fixes a bug related to determining if the data message returning from memory is for a cached or uncached request. Basically, the current MSHR in the CCE is not guaranteed to be related to the returning memory data response so the CCE should instead examine the data response itself to form the proper LCE Data Command message.
=> CCE: fix lce data command for uncached data in normal execution mode

bp_common/src/include/bp_common_aviary_defines.vh, bp_common/src/include/bp_common_aviary_pkg.vh, bp_common/test/Makefile.frag, bp_me/src/asm/microcode/cce/ei-tr.S, bp_me/src/asm/microcode/cce/ei.S, bp_me/src/asm/microcode/cce/mesi-tr.S, bp_me/src/asm/microcode/cce/mesi.S, bp_me/src/asm/microcode/cce/msi-tr.S, bp_me/src/asm/microcode/cce/msi.S, bp_me/src/include/v/bp_cce_pkg.v, bp_me/src/v/cce/bp_cce.v, bp_me/src/v/cce/bp_cce_msg.v, bp_me/src/v/cce/bp_cce_reg.v, bp_top/src/v/bp_clint.v, bp_top/src/v/bp_tile.v, bp_top/src/v/bp_top.v
This contains two changes:
1. Add mem_payload_width_p to bp_proc_params struct that defines the size of payload field in the CCE-MEM interface to hold the CCE's MSHR. This keeps the payload size and contents opaque. The CCE casts the bits into the MSHR format used internally.
2. A small fix to CCE microcode to avoid deadlock during startup/sync. Previously, the LCE Response buffer could fill up if the number of LCEs was greater than the number of way groups managed by each CCE. This results in deadlock during the sync routine between the CCEs and LCEs. The CCE will now wait for the sync ack after each sync command. This adds some latency to the sync sequence at startup (only time it happens), but avoids having to double or quadruple the size of the LCE Response buffer at each CCE. The …
=> Add mem_payload_width to bp_proc_params and fix CCE microcode to avoid deadlock in sync

bp_me/src/v/wormhole/bp_me_cce_to_wormhole_link_client.v, bp_me/src/v/wormhole/bp_me_cce_to_wormhole_link_master.v
This change fixes an issue with the master/client bp_me_cce_wormhole_links, where on an uncached store, the data being selected from the memory data command was the incorrect bits. The memory data command from the CCE always sends the uncached store data in the least significant 64-bits of the data field. The link master/client should always use these 64-bits as the store data when packaging the wormhole packet.
=> Uncached Store - Memory Data Command Fix

bp_be/src/include/bp_be_csr_defines.vh, bp_be/src/v/bp_be_checker/bp_be_checker_top.v, bp_be/src/v/bp_be_checker/bp_be_director.v, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_be/src/v/bp_be_top.v, bp_common/src/include/bp_common_aviary_pkg.vh
- Changing pmpaddr to warl to match spec.  
- Changing physical address space to 40 bits to increase mmio range and suss out issues of vaddr/paddr mismatch.  
- Changing mepc/mtval/mtvec storage to honor sign extension for virtual addresses and zero extension for zero extended written values.
=> Various fixes to CSR regfile 

bp_common/syn/Makefile.vcs, bp_fe/src/v/bp_fe_mem.v, bp_fe/src/v/bp_fe_pc_gen.v, bp_fe/src/v/bp_fe_top.v
while having fetches depend on icache_ready.  Because the fe_mem will conditionally accept the command, it needs to be valid-yumi instead of ready-valid.  This incurs no additional hardware cost, because pc_gen is already helpful, due to the wait state.
Give this a shot in Linux run before we merge it in, but it's passing regression locally
=> Making itlb writes unconditional

LICENSE, README.md, bp_common/src/include/bp_common_fe_be_if.vh, bp_common/src/include/bp_common_me_if.vh, docs/interface_specification.md
This is the branch we're going to use to update documentation prior to v1.0.  Let's discuss what's all necessary and push to this branch over the next week.
First thing @muwyse, could you write up the current LCE-CCE interface? The version in the Interface Specification doc is out of date (still refers to data_cmd and data_resp).  Probably just a list of what each command does and then a few examples of sequences (cache fill routine, invalidation).
=> Update documentation for release

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_req.v
This change fixes when and how the D$ issues a miss request for a load-reserved instruction.
1. The LR should miss if the block is cached read-only or if the block is not cached at all.
2. The LR must take priority over the load_miss_i signal in the LCE Request module so the request is properly issued as a store miss, which will result in the D$ receiving the block with read/write permissions.
=> fix LR not issuing as write miss when block not cached

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_fe/src/v/bp_fe_mem.v
We should prohibit memory accesses to chained chips which may not exist.  Speculative or malicious accesses to these addresses will hang the processor.
Future work is to enable foreign domains via the config bus
=> Adding access fault to invalid domain id accesses

bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_common/src/include/bp_common_csr_defines.vh, bp_common/src/v/bp_pma.v, bp_fe/src/v/bp_fe_mem.v
- Fixed not checking access faults on SC instructions
- Enabled FS and SD bits in mstatus CSR which are used by Linux to manage float context switching
- Poison I$ on access and page faults so the I$ doesn't freeze indefinitely
=> A number of unrelated fixes to FE and BE

bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_checker/bp_be_scheduler.v, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_common/src/include/bp_common_pkg.vh, bp_top/src/v/bp_clint_slice.v, bp_top/syn/flist.vcs
When we take a trap all the instructions read from FE queue should be dequeued, but flushing them zeros their `queue_v` field which causes them not to dequeued from the pipe and making problems when rolling back in the future.
Instead, we keep its `decode` field and just poison it in the calculator.
=> Dispatch packets should be poisoned instead of flushing to be dequeued  from FE queue

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
The status signals out of dcache should not depend on poison input for clarity reasons, as well as potential (and realized) timing loops.
=> Breaking timing loop in dcache

bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_common/.gitignore, bp_common/syn/Makefile.vcs, bp_common/test/Makefile, bp_common/test/Makefile.frag, bp_common/test/src/demos/Makefile, bp_common/test/src/demos/Makefile.frag, bp_common/test/src/demos/src/bs.c, bp_common/test/src/perch/start.S, bp_me/test/common/bp_cce_mmio_cfg_loader.v, bp_top/test/common/bp_monitor.cpp, bp_top/test/common/bp_nonsynth_cosim.v, bp_top/test/common/bp_nonsynth_nbf_loader.v, bp_top/test/common/dromajo_cosim.cpp, bp_top/test/tb/bp_top_trace_demo/Makefile.frag, bp_top/test/tb/bp_top_trace_demo/flist.vcs, bp_top/test/tb/bp_top_trace_demo/testbench.v, external/Makefile.tools
This PR adds the capability to run a benchmark on Dromajo(as an ISA simulator) until for a certain number of instructions and then resume with cosimulation in RTL.
To run on Dromajo and generate the checkpoint files run:
`cd bp_common/test`
`make <test>.dromajo MAXINSN=<n> MEMSIZE=<k in MB>`
This generates test files under the name `<test>.dromajo.<n>`
And then to load the state in RTL and run with cosim enabled run:
`cd bp_top/syn`
`make build.v sim.v PROG=<test>.dromajo.<n> PRELOAD_MEM_P=1 LOAD_NBF_P=1 COSIM_P=1`
This command preloads the mainram with the generated binary, and restores the processor state through the generated nbf files.
=> Check-pointing and Cosimulation with Dromajo

bp_me/src/v/cce/bp_cce.v, bp_me/src/v/cce/bp_cce_msg.v, bp_me/src/v/cce/bp_cce_msg_cached.v
These used to be connected for fifo, so rv& was appropriate.  Now, it's connecting to cache / clint, so r->v has clearer intent.
=> Changing interface handshake on cce cmd outputs

.gitlab-ci.yml, Makefile
This should get of those false negative failures where you update a tool / test and it passes locally but fails in CI.
=> Adding autotrigger for CI

bp_top/syn/flist.vcs
These modules are being updated upstream. For now, they're unused so remove from flist
=> Removing wormhole streamers from flist

.gitlab-ci.yml, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_req.v, bp_fe/src/v/bp_fe_lce_req.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v
Inferred latches snuck in for the pad fields of the messages.  Easy fix is setting pad to 0.
Also minor CI enhancement where hotfix reuses the cache from dev instead of building its own toolchain.
=> Fixing inferred latches

bp_be/src/v/bp_be_mem/bp_be_mem_top.v
The issue was that when we changed the fencei instruction from a privileged instruction to a dcache instruction, it then started doing a tlb lookup in parallel to the fence instruction, as if it were a load.
This is fine for the tests with VM disabled because the tlb lookup is passthrough anyway.  But VM tests immediately faulted.  Simultaneously, the tests are poorly written, such that any machine unknown supervisor mode exception will cause a finish, with whatever register happens to correspond to the exit code (in this case ra)
=> Disabling tlb lookup on fencei instructions

bp_common/syn/Makefile.common, bp_top/test/common/bp_nonsynth_host.v
**Not fully tested**
Originally tests PASS when LSB of returned finish packet is 1'b0, which may not be a good way of checking. In this PR, PASS means returned value in finish packet is 64'b0.
=> Nonsynth Host Enhancement

bp_common/syn/Makefile.vcs, bp_common/syn/Makefile.verilator, bp_common/test/Makefile, bp_common/test/cfg/cosim.cfg, bp_top/test/tb/bp_processor/testbench.v, bp_top/test/tb/bp_softcore/testbench.v
Added a default input config file to Dromajo to be used during cosim when not running a generated checkpoint.
=> Added default Dromajo cfg file

bp_me/src/v/cce/bp_cce_fsm.v
Update the FSM CCE.
regress_riscv.v/sc and regress_beebs.v passed
spot checks on 2, 4, and 8 core using atomic_queue_demo and mc_xxx tests passed under VCS
This change commits only the updates to the FSM CCE and does not replace the ucode CCE with the FSM CCE in the design. Additional (simple) change is required to substitute in the FSM CCE for use.
=> Update FSM CCE for dev

bp_be/src/v/bp_be_mem/bp_be_mem_top.v
Originally, when some signals are X, it will be evaluated to ~X which is still X, printing out warning message in simulation.
This fix ensures that when reset_i !== 1'b0 (when it is 1'b1, X or Z), assertion will not be triggered.
=> Fix be_mem_top Assertion

bp_common/test/Makefile
This PR adds the functionality to generate multiple checkpoints from a program for every N instructions executed.
`make <test>.dromajo DUMP_PERIOD=<n>`
=> Added periodic Dromajo checkpoint dumps

.gitlab-ci.yml, bp_common/src/include/bp_common_aviary_defines.vh, bp_common/src/include/bp_common_aviary_pkg.vh, bp_me/src/v/cce/bp_cce_fsm.v, bp_me/src/v/cce/bp_cce_msg.v, bp_me/src/v/cce/bp_cce_wrapper.v, bp_me/syn/Makefile, bp_top/src/v/bp_l2e_tile.v, bp_top/src/v/bp_tile.v, bp_top/syn/flist.vcs, bp_top/test/tb/bp_processor/testbench.v
This change adds the fsm_cce_p parameter to bp_params_p, which is used to determine which CCE variant is instantiated in the design. A new bp_cce_wrapper module is added that does the conditional instantiation of the CCE type. Using a wrapper encapsulates the conditional instantiation and provides a common module for nonsynth tracers to bind to.
New configs are added that use the FSM CCE instead of microcode CCE.
PR addresses Issue #417
=> Add configs that use FSM CCE, parameterized CCE instantiation

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
We need to poison the v_i to the long pipe when instruction is not valid due to a branch mispredict.
=> Poison the Long Pipe Input

.gitlab-ci.yml
This change fully specifies the TB and CFG params for the Makefiles for all tests in the gitlab CI file. Without fully specifying both parameters, some tests were running with TB=bp_processor and CFG=e_bp_softcore_cfg. I don't believe this is intended to be a supported TB/CFG pair.
Notably, the TB/CFG pair of bp_processor & e_bp_softcore_cfg results in the regress_riscv.v target failing some tests, but this does not appear to be detected by CI. Specifically, the rv64ui-v-* tests and rv64ui-p-fence_i tests report failures when I run them locally. Changing CFG to e_bp_single_core[_ucode_cce]_cfg results in all tests passing.
This pipeline: https://gitlab.com/black-parrot/black-parrot/pipelines/135024242 shows the CI tests reporting pass at a commit where there are failing tests due to the …
=> fully specify TB and CFG in CI file for tests

bp_me/src/v/cce/bp_cce_spec_bits.v
This change removes write to read forwarding in the CCE spec bits to break a timing loop.
=> remove write to read forwarding in spec bits

bp_common/software/py/pc_histogram.py
Adds Black Parrot PC Histogram profiler to parse the operation trace and generate basic block execution count for the entire network as well as for each bp core separately.
=> Brings PC Histogram to Black Parrot

bp_common/software/py/blood_graph.py
Adds three options for choosing the timing window of blood graphs:
--trace: default, use the first and last trace from the trace file as start and end cycle
--stats: if the stats file is given as input, use the first kernel_start and last kernel_end stat --> if given as input, it overrides option 1 and narrows the bloodgraph to the window in which the tiles are actually running the kernel
--cycle: custom start/end cycles given by the user which overrides the other two
Minor restructuring of functions and variables as well.
=> Extending blood graph timing window options

bp_me/software/scripts/run.sh, bp_top/test/tb/bp_processor/testbench.v
This change instantiates the nonsynth cosim module in bp_processor testbench only if the core count is equal to one, since it is not expected to work for multicore.
=> Disable cosim for multicore builds

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
This change adds missing type casts in the dcache.
=> apply bp_coh_states_e cast in dcache

.gitlab-ci.yml
Re-enable CI runs of multicore tests and coremark using Verilator
=> enable verilator CI for multicore, beebs, and coremark

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/syn/flist.vcs, bp_fe/src/v/bp_fe_icache.v
The updated fe_dev branch from my fork contains the reshuffled icache and dcache, both with tag compare moved from the tv stage to the tl stage. In the case of the dcache, miss detection is still handled in tv. Additionally, there may be some accidental changes to submodules or the testing infrastructure, but as of my last commit the testing infrastructure worked and the softcore was passing the beebs and riscv-tests regressions.
=> Retime I$ and D$ tag comparison

bp_top/src/v/bp_cacc_vdp.v
This PR is to fix the change that was missed in the updates to the D$.
While making this change we discovered that the A$ wasn't effectively using the parameters defined for it in the configuration but ends up using the D$ parameters. 
An issue (#472) was opened for this.
=> Fixing the LCE-A$ mem_pkt interface to valid->yumi 

bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.v, bp_be/src/v/bp_be_checker/bp_be_director.v
- Fixes bad case statement comparison
- Fences go to mem pipe, not control pipe
- //synopsys translate_off unguarded nonsynth block
=> Dev hotfix vivado synthesis

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_cmd.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_req.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_be/src/v/bp_be_top.v, bp_be/syn/flist.vcs, bp_be/test/tb/bp_be_dcache/wrapper.v, bp_common/src/include/bp_common_aviary_defines.vh, bp_common/src/include/bp_common_aviary_pkg.vh, bp_common/src/include/bp_common_cache_service_if.vh, bp_common/test/mem/hello_world.dump, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_lce.v, bp_fe/src/v/bp_fe_lce_cmd.v, bp_fe/src/v/bp_fe_lce_req.v, bp_fe/src/v/bp_fe_mem.v, bp_fe/src/v/bp_fe_top.v, bp_fe/syn/flist.vcs, bp_fe/test/tb/bp_fe_icache/wrapper.v, bp_me/src/v/cce/bp_uce.v, bp_top/src/v/bp_cacc_vdp.v, bp_top/src/v/bp_core.v, bp_top/src/v/bp_core_minimal.v, bp_top/src/v/bp_softcore.v, bp_top/syn/Makefile, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_cache_tracer.v, bp_top/test/common/bp_nonsynth_if_verif.v
1. fill mask added in data_mem_pkt to indicate the banks being filled
2. Data field in data_mem_pkt is changed to fill width from data_width
3. cache_req_critical signal is added
4. In-progress registers indicating the info of the only one outstanding missed cacheline are added
5. Corresponding logic like generating writemask to SRAM based on fill mask and checking hitted bank is filled or not are added
=> Add partial fill support to Cache Service Interface

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
This caused issues where things wouldn't quite be flushed in some situations, leading to a spurious long instruction writing back.  Interestingly, cosim had a hard time finding it, because the writeback happens out of band, so the commits looked fine.
=> Fix poison condition for long latency instructions

Makefile, bp_be/src/v/bp_be_calculator/bp_be_pipe_ctrl.v, bp_common/test/Makefile.frag, bp_common/test/Makefile.tests
RISC-V spec defines JALR to zero LSB to 0, to prevent misalignment
Fixes #400 #402
=> Fixing LSB of branch target to always be 0

bp_me/syn/Makefile, bp_me/test/tb/bp_cce/Makefile.params, bp_me/test/tb/bp_cce/testbench.v, bp_top/test/tb/bp_tethered/testbench.v
This change adds back the CCE tracer to the bp_top testbench, instantiating only if CCE_TRACE_P=1 is passed on the command line.
Setting cce_trace_p to 1 for invalid configs (e.g., softcores) results in a build error since the CCE does not exist and therefore the bind statement fails. I think this is acceptable, as the alternative is to guard the tracer instantiation by checking the provided config, which is a burden to maintain as configs are added/changed/removed.
This change also fixes up the ME bp_cce testbench to re-enable the CCE and LCE tracers.
=> fix CCE and LCE tracing in bp_top and bp_me testbenches

bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
RISC-V defines that funct3 for JALR == 3'b000.  In our decoder, we did not make this assertion and just checked the opcode.
```
`RV64_JALR_OP :
begin
decode.pipe_ctrl_v = 1'b1;
decode.irf_w_v    = 1'b1;
decode.fu_op      = e_ctrl_op_jalr;
decode.baddr_sel  = e_baddr_is_rs1;
end
```
Fixes #497 , test added
=> Detecting illegal jalr

bp_top/test/tb/bp_tethered/Makefile.testlist
Minor path issue.  riscvdv tests should generate and run properly now
=> Fixing path issue for riscvdv tests

README.md
IEEE micro paper is in early access so it can officially be cited as the canonical BlackParrot paper
=> Adding citation information

bp_me/src/v/cce/bp_cce_loopback.v, bp_me/src/v/cce/bp_uce.v, bp_top/src/v/bp_tile.v, bp_top/src/v/bp_unicore.v, bp_top/syn/flist.vcs
Basically, the issue here is that local requests to in-core configuration registers will freeze the system if they don't correspond to a sink (cfg, clint, cache, etc.).
Instead, we can use this lightweight loopback module which just forwards back the request to the sender.  This makes a more robust system, since we don't have error responses in the bedrock network.
=> Adding CCE loopback module

bp_be/src/v/bp_be_mem/bp_be_csr.v
We don't actually support PMP, and supporting the CSR without trapping on violations is a violation of the spec.
=> Remove defunct pmp csr support

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_cmd.v, bp_common/src/include/bp_common_aviary_pkg.vh, bp_common/src/include/bp_common_cache_service_if.vh, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_lce_cmd.v, bp_me/src/v/cce/bp_uce.v, bp_top/syn/flist.vcs
UCE FSM modification for multicycle fill/evict
1. States for following func are changed:
cache flush with dirty data (e_flush_write)
cache miss load (e_read_req) 
cache miss load with dirty data replacement (e_writeback_read_req, e_writeback_write_req)
2. 2 counters are added, fill_cnt and mem_cmd_cnt, to track the progress of multicycle fill/evict
3. A new register, mem_cmd_done_r is added. In multicycle fillm, this 1-bit reg indicates whether all the mem_cmd are sent. Together with this register, mem_cmds can be sent as long as L2 is ready, avoiding potential latency.
=> UCE FSM modification for multicycle fill/evict

bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_checker/bp_be_director.v, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_common/src/include/bp_common_fe_be_if.vh, bp_fe/src/v/bp_fe_pc_gen.v
The riscv-v spec dictates that SATP write must be reflected in immediately following fetches. So we flush the pipeline to force a refetch with address translation enabled
=> Flush the pipeline on SATP write

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/syn/flist.vcs, bp_common/test/Makefile.tests, bp_fe/src/v/bp_fe_icache.v, bp_fe/syn/flist.vcs, bp_me/syn/flist.vcs, bp_top/syn/flist.vcs
This PR converts the caches to one-hot encoding for their muxes.  In order to support this changes, we need to modify our banking scheme from bank_id = way_id ^ word_offset to bank_id = way_id [mod +] word_offset.  For this we use the one-hot adder module recently added to basejump_stl.
This should give a fairly large critical path improvement with little area overhead.
@Shashank-Vijay @sripathi-muralitharan Take a look to see if the changes make sense?
@taylor-bsg do you have an idea if there are more efficient ways to synthesize circular shift? We should add a barrel shifter to basejump_stl, but I'm guessing this will synthesize to the same.
```
// Circular left shift
assign bar = (foo << x) | (foo >> WIDTH-x)
// Circular right shift
assign bar = {foo, foo} >> x;
```
=> One-hotifying caches

bp_top/test/common/bp_nonsynth_cosim.v, bp_top/test/common/dromajo_cosim.cpp, bp_top/test/tb/bp_tethered/Makefile.params, bp_top/test/tb/bp_tethered/Makefile.testlist, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator, bp_top/test/tb/bp_tethered/testbench.v
This PR adds the capability to run multicore tests with the Dromajo cosimulation and also lets us create checkpoints for these tests.
- Bumped Dromajo with multicore capability
- Initialize the Dromajo cosimulation instance using RTL parameters as input flags
- Minor testbench and Makefile changes (Added `SAMPLE_NCPUS` flag for checkpoint generation)
=> Adding Multicore Cosimulation and Checkpointing

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_be/src/v/bp_be_top.v, bp_be/syn/flist.vcs, bp_be/test/tb/bp_be_dcache/testbench.v, bp_be/test/tb/bp_be_dcache/wrapper.v, bp_common/src/include/bp_common_aviary_defines.vh, bp_common/src/include/bp_common_aviary_pkg.vh, bp_common/src/include/bp_common_cache_service_if.vh, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_mem.v, bp_fe/src/v/bp_fe_pc_gen.v, bp_fe/src/v/bp_fe_top.v, bp_fe/syn/flist.vcs, bp_fe/test/tb/bp_fe_icache/testbench.v, bp_fe/test/tb/bp_fe_icache/wrapper.v, bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce.v, bp_me/src/v/lce/bp_lce_cmd.v, bp_me/src/v/lce/bp_lce_req.v, bp_top/src/v/bp_cacc_vdp.v, bp_top/src/v/bp_core.v, bp_top/src/v/bp_core_minimal.v, bp_top/src/v/bp_unicore.v, bp_top/syn/Makefile, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_cache_tracer.v, bp_top/test/common/bp_nonsynth_if_verif.v, bp_top/test/tb/bp_tethered/testbench.v
Rebase the work of IF modification for partial fill and UCE FSM modification for multi-cycle fill/eviction to me_dev. Tested on unicore with multicycle-fill, and on single core with full cache block fill.
=> Partial Fill / Eviction Cache Service Interface Modification

bp_be/src/include/bp_be_mem_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_be/src/v/bp_be_mem/bp_be_mem_top.v, bp_be/src/v/bp_be_top.v, bp_be/test/common/bp_be_nonsynth_vm_tracer.v, bp_common/src/v/bp_tlb.v, bp_fe/src/v/bp_fe_mem.v, bp_top/src/v/bp_cacc_vdp.v, bp_top/src/v/bp_piton_top.v, bp_top/src/v/bp_softcore.v, bp_top/src/v/bp_tile.v, bp_top/test/common/bp_nonsynth_host.v, bp_top/test/tb/bp_tethered/testbench.v
This PR introduces the fix for a bug that was found in bare metal execution where the specification is to use 64-bit effective addresses instead of 39-bit virtual addresses.
This PR also closes issues #393 and #394.
=> Using effective addresses instead of virtual addresses in the MMU

.gitmodules, bp_me/src/v/wormhole/bp_me_addr_to_cce_id.v
To solve integration issues with other projects using basejump stl, our new policy is to track master as closely as possible.  Leaving the BlackParrot basejump fork up for legacy builds
=> Redirect basejump to upstream master

bp_be/test/common/bp_be_nonsynth_vm_tracer.v, bp_common/src/v/bp_tlb.v, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_mem.v, bp_fe/syn/flist.vcs, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_cache_tracer.v, bp_top/test/tb/bp_tethered/testbench.v
Bypass I-TLB and tag_mem when possible. In addition, select the necessary bank of data_mem.
When incoming vaddr tag == previously fetched valid vtag and we’re not doing itlb_fence or itlb_fill, we bypass the i-tlb
If we bypass the i-tlb, then the physical tag is always valid (ptag_v_li) and the physical tag (ptag_li) is previously stored ptag. Note itlb_r_v_lo = 0 when bypass is enabled
While we’re performing a itlb_fence or itlb_fill, we do not bypass
Furthermore, we invalidate the current vtag that’s going to be stored in the prev_fetch_vtag_r
If a fetch results in a miss, we invalidate the vtag in prev_fetch_vtag_r. Note that itlb_miss_lo is determined on the same cycle as we’re storing prev_fetch_tag
When incoming vaddr index == previous valid index and we’re not writing to or …
=> ITLB / I$ power optimizations

bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce.v, bp_me/src/v/lce/bp_lce_cmd.v, bp_me/src/v/lce/bp_lce_req.v
- Uncached stores now have 1/cycle throughput in LCE
- Removing bypass paths from cache engines (these paths were critical in both unicore and multicore)
- Clarified the v_r semantics which will help with the negedge 2-cycle loads
These will cause a minor IPC regression on writebacks and flushes, but we can recover it with bypass flops using the same v_r semantics if we find the performance impact to be too great
=> Cache engine PPA fixes

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_checker/bp_be_detector.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_wbuf.v, bp_be/test/tb/bp_be_dcache/wrapper.v, bp_fe/src/v/bp_fe_icache.v, bp_me/src/v/cache/bp_me_cache_dma_to_cce.v, bp_me/src/v/cce/bp_cce_dir_segment.v, bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce.v, bp_me/src/v/lce/bp_lce_cmd.v, bp_me/src/v/lce/bp_lce_req.v, bp_top/src/v/bp_core.v, bp_top/src/v/bp_unicore.v, bp_top/test/common/bp_nonsynth_core_profiler.v, bp_top/test/tb/bp_tethered/testbench.v
This PR provides the data cache with a 2-cycle load-use latency. It does so by shifting the data and tag memories to a negative edge read, splitting the extra cycle into 1/2 cycle for address calculation and 1/2 cycle for data muxing. This requires some complexity in the cache engines to synchronize between the clock edges and provide a full cycle read.  Another change is to make the data muxing in the D$ more efficient to better use that 1/2 cycle.
It's been pushed through the backend flow without additional critical paths and pushed through the FPGA flow to boot linux
=> 2-cycle load-use for D$

.gitmodules, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_common/test/Makefile.tests, bp_common/test/src/bootrom/Makefile, bp_common/test/src/bootrom/bootrom.S, bp_common/test/src/bootrom/link.ld, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_mem.v, bp_fe/src/v/bp_fe_pc_gen.v, bp_me/src/v/cache/bp_me_cache_dma_to_cce.v, bp_me/src/v/cce/bp_cce_dir_segment.v, bp_me/src/v/cce/bp_uce.v, bp_me/src/v/wormhole/bp_me_addr_to_cce_id.v, bp_top/test/common/bp_nonsynth_host.v, bp_top/test/tb/bp_tethered/Makefile.vcs
This is the first step in enabling execution-driven debug mode.  This PR enables program execution from uncached regions and adds a boot rom flow, which can be used to add arbitrary code execution to the boot flow, before loading the actual program in DRAM
=> Enabling option to boot from synthesizable bootrom 

bp_be/src/include/bp_be_ctl_defines.vh, bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_checker/bp_be_detector.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_mem/bp_be_ptw.v, bp_be/test/tb/bp_be_dcache/testbench.v, bp_be/test/tb/bp_be_dcache/wrapper.v, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_mem.v, bp_top/test/tb/bp_tethered/testbench.v
The load-fwd path is the current critical path in the BE.  Subword loads are not usually in critical loops.  Therefore, we allow early 2-cycle double word loads and delay subword loads by a cycle.  Float loads will also be on the 3-cycle path.
Changes:
- Update D$ description block
- Added early/final data ports to the D$
- Updated hazard detection logic
- Update D$ testbench to not rely on zero store data and use final data
- Removed misleading cache miss signal, since it doesn't indicate whether a miss is due to poison or tag miss
=> Delaying byte muxing by a cycle

bp_top/src/v/bp_unicore.v, bp_top/test/tb/bp_tethered/wrapper.v
I/O width is the same as fill width. In this fix, we adjust to the full protocol width the wrapper.  This hack will go away when header/data ports are separated
=> Fixing I/O cmd/resp width to fill width

bp_me/src/v/cce/bp_uce.v, docs/interface_specification.md
This PR adds support for sending the critical fill address request first over the mem_cmd signal in the UCE. The higher fill addresses follow and a wrap around to the lower fill addresses occurs once the highest fill address of the current block is sent.
=> Wrap around logic for ordering addresses sent to the memory

bp_me/src/include/v/bp_mem_wormhole.vh, bp_me/src/v/wormhole/bp_me_cce_to_mem_link_client.v, bp_me/src/v/wormhole/bp_me_cce_to_mem_link_master.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v, bp_top/src/v/bp_cacc_tile.v, bp_top/src/v/bp_cacc_vdp.v, bp_top/src/v/bp_io_tile.v, bp_top/src/v/bp_sacc_tile.v, bp_top/src/v/bp_sacc_vdp.v, bp_top/src/v/bp_tile.v, bp_top/syn/flist.vcs
This PR is mostly in preparation for wormhole streamer changes, which require separation of header/data ports for various modules.  No functional change / no PPA change.
- Separating out header / data in wormhole definitions
- Fixing wormhole padding definitions in bp_mem_wormhole.vh (Fixes #464)
- Refactored wormhole encoders to only translate header->header
- Minor bug fix: Line 512 of bp_tile _lo -> _v_lo
=> Separate out header / data from wormhole definitions

bp_me/src/v/cce/bp_cce_msg.v
This PR closes #581 by adding a memory credit counter to the ucode CCE. It also fixes the transition from uncached only to normal operation mode.
=> add memory credit counter to ucode CCE

bp_me/src/v/cce/bp_cce.v, bp_me/src/v/cce/bp_cce_fsm.v, bp_me/src/v/cce/bp_cce_inst_stall.v, bp_me/src/v/cce/bp_cce_msg.v
This change forces the ucode CCE normal mode to account for available memory credits when sending a mem_cmd, stalling the ucode engine if there are no credits available.
This change also adds memory credit flow control to the FSM CCE.
=> enforce memory credits on mem_cmd for normal mode and in FSM CCE

bp_be/src/include/bp_be_ctl_defines.vh, bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v, bp_be/src/v/bp_be_checker/bp_be_director.v, bp_be/src/v/bp_be_mem/bp_be_csr.v
Minor fix to remove the "instr_v" field from various structures.  There were some weird edge cases differentiating between v and instr_v, now they are all combined into v.  (tested on linux boot)
=> Removing instr_v field from BE

bp_be/syn/flist.vcs, bp_common/src/include/bp_common_aviary_pkg.vh, bp_fe/syn/flist.vcs, bp_me/src/v/cache/bp_me_cache_slice_burst.v, bp_me/src/v/wormhole/bp_lite_to_stream.v, bp_me/src/v/wormhole/bp_stream_to_lite.v, bp_me/syn/flist.vcs, bp_top/src/v/bp_tile.v, bp_top/syn/flist.vcs, bp_top/test/tb/bp_tethered/Makefile.cfgs
This PR replaces the ser/des of the L2 cache fill.  It leverages the wormhole streamer modules (needs this PR to go through) https://github.com/bespoke-silicon-group/basejump_stl/pull/232 to basically gearbox between the cache adapter and the wormhole router directly.
It also adds a missing configuration for multicore without L2.
=> Using wormhole streamers for DMA

bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce_cmd.v
...in the UCE and LCE.  This PR simply raises critical signal when the word is being written in the data_mem_pkt.
(PR is made to FE dev because it is first in a series of related PRs)
=> Rudimentary critical word first support

bp_be/src/include/bp_be_ctl_defines.vh, bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v, bp_be/src/v/bp_be_checker/bp_be_director.v, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_common/src/include/bp_common_fe_be_if.vh, bp_common/src/v/bp_tlb.v, bp_fe/src/v/bp_fe_mem.v
This PR adds an I$ miss message to the FE-BE interface, as well as the infrastructure to redirect the FE based on it. The message is unused and will be implemented in the next PR
=> Adding I$ miss message and backend infrastructure

bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator
Make OVERRIDE_BOOTROM parameter default to 1 so bootroms build for tests in bp_top
=> override bootrom by default for bp_top sim

bp_common/test/src/bootrom/Makefile, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator
Make bootrom build process happen in user-specified directories to avoid thrashing when running tests concurrently.
=> bootrom build fixes

bp_me/src/v/wormhole/bp_me_cce_to_mem_link_bidir.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_cmd.v, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_mem_resp.v
Upstreams fixes to for flit width parameters and use in a few of the wormhole modules.
=> upstream bugfixes from me_dev for wormhole modules

bp_common/test/src/demos/src/sample.c
The test is hanging at the end of runtime due to missing   bp_finish(0);. Adding this will make it terminate correctly.
=> Adding bp_finish at the end of test

bp_be/src/include/bp_be_internal_if_defines.vh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.v, bp_be/src/v/bp_be_checker/bp_be_director.v, bp_be/src/v/bp_be_checker/bp_be_scheduler.v, bp_be/src/v/bp_be_mem/bp_be_csr.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce_cmd.v
- Adds writeback packet to memory pipe
- Rolls back on D$ miss, but still dequeues
- Adds rudimentary critical word first and data replication to support this
- Minor change to commit packet to clarify difference between commit and trap
Fixes non-idempotency of uncached loads/atomics
=> Adding writeback packet to memory pipe

.gitlab-ci.yml, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_common/src/include/bp_common_aviary_pkg.vh, bp_common/syn/Makefile.dc, bp_fe/src/v/bp_fe_icache.v, bp_me/src/v/cache/bp_me_cce_to_cache.v, bp_me/src/v/cce/bp_cce_loopback.v, bp_me/src/v/lce/bp_lce.v, bp_me/src/v/lce/bp_lce_cmd.v, bp_me/src/v/lce/bp_lce_req.v, bp_top/src/v/bp_cfg.v, bp_top/src/v/bp_clint_slice.v, bp_top/src/v/bp_tile.v, bp_top/src/v/bp_unicore.v, bp_top/test/common/bp_nonsynth_cache_tracer.v, bp_top/test/common/bp_nonsynth_if_verif.v, bp_top/test/tb/bp_tethered/Makefile.cfgs, ci/weird_config.sh
This PR adds a fix for the l1_medium and l1_small cache configs that were found to be broken. A new l1_tiny config will follow in a future PR as well. 
The main reason for these configs to break was that we currently strongly require all caches - I$, D$ and A$ (Accelerator cache) to have the same parameters (the blockwidth specifically).
=> Fixing Weird Cache Configs

bp_common/src/include/bp_common_aviary_pkg.vh, bp_fe/src/include/bp_fe_defines.vh, bp_fe/src/v/bp_fe_bht.v, bp_fe/src/v/bp_fe_btb.v, bp_fe/src/v/bp_fe_pc_gen.v
- Absorbs valids into BTB RAM
- Converts BHT to 1r1w_sync
- Adds initialization FSMs to BHT and BTB
- Makes BHT updates idempotent, fixes #286
=> Harden predictors

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_top.v, bp_be/test/tb/bp_be_dcache/testbench.v, bp_be/test/tb/bp_be_dcache/wrapper.v, bp_common/src/include/bp_common_cache_service_if.vh, bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce.v, bp_me/src/v/lce/bp_lce_cmd.v
- Adds tag info to the cache service struct
- Updates this struct in cache engines
Not used for anything right now, but enables extra state (coherence or otherwise) to be stored in the tag, useful for certain classes of cache engine. For instance, a system where true tags are stored in L1 rather than shadow tags.
=> Adding full tag info to the cache service interface

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v, bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v, bp_be/src/v/bp_be_top.v, bp_be/test/tb/bp_be_dcache/wrapper.v, bp_fe/src/v/bp_fe_icache.v, bp_fe/src/v/bp_fe_top.v, bp_fe/test/tb/bp_fe_icache/wrapper.v, bp_me/src/v/cce/bp_uce.v, bp_me/src/v/lce/bp_lce.v, bp_me/src/v/lce/bp_lce_req.v, bp_top/src/v/bp_core.v, bp_top/src/v/bp_core_minimal.v, bp_top/src/v/bp_unicore.v
This PR includes 2 updates:
1. Change the cache_req interface between L1 cache and UCE from ready-then-valid to valid-then_yumi.
2. UCE sends cache_req_complete_o to L1 cache and then write back dirty data, so L1 cache can restart early.
The updates is test with cache_hammer, riscv_testlist and beebs testlist with full block size and sub-block size. A possible known issue is that the credits counter may overflow when fill_width_p==64. This issues results from the 8 credits for dirty data writeback may come back later than new credits issued by the next command, but this is no longer a concern if the when it is merged with the stream pump updates because it will only consume 1 credit.
=> Fix cache late restart due to dirty data writeback

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
As mentioned in the comments, cache parameters should satisfy the following conditions. 
The dcache supports multi-cycle fill/eviction with the following constraints:
- bank_width = block_width / assoc >= dword_width
- fill_width = N*bank_width <= block_width
But whenever an incorrect set of parameters are used, it will result in a compilation error(in verilator). 
To resolve this issue, one option is to edit the parameters such that it won't result in a compile error even when the conditions are not met. Other option is to introduce a compile time check of these conditions. 
This PR is for the second option, to communicate the cause of this error to the user, the above compile time check can be used. (Because generate blocks are resolved at compile time).
=> Adding a compile time check for cache parameter conditions

bp_common/src/include/bp_common_aviary_pkg.sv, bp_fe/src/v/bp_fe_bht.sv, bp_fe/src/v/bp_fe_btb.sv
- Fixes simultaneous read/write in predictors
- Shortens btb tag for optimal hardened RAM dimensionality
=> Tapeout fixes

.gitmodules, bp_common/src/include/bp_common_aviary_pkg.sv, bp_common/src/include/bp_common_cache_engine_if.svh, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/tb/bp_fe_icache/Makefile.params, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce.sv, bp_top/test/tb/bp_tethered/Makefile.cfgs, ci/weird_config.sh
This PR adds support for a tiny cache - 4KB and a corresponding tiny config (reflects only the tiny icache changes) that is supported only in the UCE. 
A similar change for the D$ will soon follow in a future PR.
=> Tiny Instruction Cache

bp_top/test/common/bp_nonsynth_host.sv
Writing to (0x0010_3000+core_id) writes to stdout.core_id. Writing to (0x0010_1000) writes to stdoutglobal.out in addition to simulation terminal out. Could be useful when debugging multicore programs.
=> replacing #674 write bp_top/nonsynth output to "global" file; separate files for each core; option of choosing either

.gitlab-ci.yml, bp_be/src/include/bp_be_internal_if_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_director.sv, bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv, bp_be/src/v/bp_be_top.sv, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_cosim.sv
Adds an integer and floating point scoreboard. For now, only used for IDIV and FDIV.  Expected minor performance improvements.
Before merging, need to figure out how to adjust cosim module to see in-order writebacks.  Most like need to reorder them in the non-synth module.
Partially in support of #718
=> Adding scoreboards for idiv and fdiv

bp_be/src/v/bp_be_calculator/bp_be_fp_to_rec.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_be/src/v/bp_be_calculator/bp_be_rec_to_fp.sv
On Vivado, this bug causes the fraction part of the result to be all-zeros when converting between single and double precision floating-point numbers.
=> FPGA Signal Alignment Bug

bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_common/src/include/bp_common_csr_defines.svh, bp_top/test/tb/bp_tethered/testbench.sv
- MPRVEN initial value should be 0, since we want to disable translation during debug mode
- disable mprv-based translation during debug mode
- Also small fix to watchdog timer, which should better detect "hardware idle loops"
=> Hotfixes for cosim

bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
- Delays byte and half muxing by a cycle
- Small IPC decrease, takes 4 muxes off the critical path (sign-extension + word selection)
=> Delaying byte and half mux-ing by a cycle

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_director.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_top.sv
This PR blocks interrupts while there's a cache replay being performed. This is necessary for making sure that uncached operations are not repeated, which can break things in non-idempotent remote memory space.  Slight penalty for interrupt responsiveness, definitely a bandaid fix until we get non-blocking loads
=> Blocks interrupts on pending cache replay

bp_me/src/v/cache/bp_me_cache_slice.sv, bp_me/src/v/wormhole/bp_lite_to_stream.sv, bp_me/src/v/wormhole/bp_stream_to_lite.sv, bp_top/syn/flist.vcs
This PR is aimed at fixing issue #730.
In current design of lite to stream modules, header and data buffers account for a majority of area consumption. Also, a bubble is introduced between consecutive requests, which is very inefficient, especially for uncached requests.
This PR replaces the header fifo with bypass registers, and make use of the sipo/piso_passthrough_dynamic to hold the data. These changes not only reduce the area consumption of the conversion modules, but also eliminate the bubbles between consecutive requests and improve the performance.
=> Remove Buffering in lite to stream modules

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_common/src/include/bp_common_bedrock_if.svh, bp_common/src/include/bp_common_bedrock_pkgdef.svh, bp_common/src/include/bp_common_cache_engine_if.svh, bp_fe/src/v/bp_fe_icache.sv, bp_me/src/v/cache/bp_me_cache_slice.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_top/src/v/bp_clint_slice.sv, bp_top/test/common/bp_nonsynth_cache_tracer.sv
This PR adds AMO subop types and cache req metadata changes needed for L2 atomic support. I believe it has no functional changes as currently written.
=> Adding AMO subop types and cache req metadata updates

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv, bp_be/src/v/bp_be_checker/bp_be_cmd_queue.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_director.sv, bp_be/src/v/bp_be_top.sv, bp_top/syn/flist.vcs
Replays exceptions and special instructions before they commit, if the FE cmd queue is full. This is necessary if the FE applies any back pressure.  Currently, we provision enough space in the fifo such that it cannot fill by construction, but this approach is more flexible.
fixes #443
=> Adding replay on full FE cmd

bp_top/src/v/bp_tile.sv
The `bsg_mux_one_hot` module doesn't generate a valid output when multiple select lines are high. So we have to do the selection based on the yumi signals that are one-hot.
Also fixes the multicore Linux boot.
=> Select the correct mem_resp on multiple valid sources

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_common/src/include/bp_common_bedrock_if.svh, bp_common/src/include/bp_common_bedrock_pkgdef.svh, bp_common/src/include/bp_common_cache_engine_pkgdef.svh, bp_me/src/v/cache/bp_me_cache_slice.sv, bp_me/src/v/cce/bp_cce_fsm.sv, bp_me/src/v/cce/bp_cce_reg.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv, bp_me/test/common/bp_me_nonsynth_cce_tracer.sv, bp_top/src/v/bp_clint_slice.sv, bp_top/test/tb/bp_tethered/testbench.sv, docs/interface_specification.md
Minor fixes
- Need to read from tag mem on L2 ops for self-invalidation
- Add flush to dirty signal to prevent speculative dirtying
- Clarified stat mem update using fast_read / fast_write
- Don't write stat mem on fencei ops
- Combining amo_noreturn, wt_req and uncached_store
=> Minor fixes to memory management in D$

bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_common/src/include/bp_common_cfg_bus_pkgdef.svh, bp_common/src/v/bp_mmu.sv, bp_common/src/v/bp_pma.sv, bp_fe/src/include/bp_fe_icache_pkgdef.svh, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/tb/bp_fe_icache/testbench.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/lce/bp_lce_req.sv
- Adds fetch and fill ops to the I$
- Adds a nonidempotency PMA (tied to off-chip space currently)
- Adds a mode where all I$ misses are treated as speculative
- Minor modification to LCE to support both modes
=> Fixes non-idempotency in the I$

bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv, bp_common/src/v/bsg_mem_1r1w_sync_mask_write_bit_reshape.v, bp_common/syn/Makefile.vcs, bp_fe/src/v/bp_fe_bht.sv, bp_fe/src/v/bp_fe_btb.sv, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/src/v/bp_fe_top.sv, bp_top/syn/flist.vcs
- Adds a memory reshaping module
- Reshapes BHT to 64-bit wide
- Adds conflict-based back-pressure in bht and btb
- Fixes a hidden X in the br_pkt exposed by these metadata changes
depends on #772 to prevent deadlock
=> Reshaping BHT

bp_me/test/common/bp_mem.sv
Default dram_pkg is non-existent, at least until they invent high-memory-bandwidth DRAM
=> Fix typo in bp_mem

bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_me/src/v/cce/bp_uce.sv
Previously, dispatch would be blocked if there was an interrupt while a cache request was being replayed.
RTL is good to go, but needs a test.  Maybe a bunch of L1 amoadds with an interrupt timer going off (edited)
=> Fixing replay pending bug

bp_be/syn/flist.vcs, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_fe/syn/flist.vcs, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/syn/flist.vcs, bp_top/src/v/bp_cfg.sv, bp_top/src/v/bp_clint_slice.sv, bp_top/src/v/bp_l2e_tile.sv, bp_top/src/v/bp_loopback.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_unicore.sv, bp_top/syn/flist.vcs
The response fifos here are unnecessary. This PR removes them with a slight modification to how the arbiter is used
=> Minimizing arbitration near cache engines

bp_common/src/include/bp_common_defines.svh
Noticed this as I was messing with includes elsewhere. `bp_common_defines.svh` includes itself, which doesn't have an effect anyway due to the header-guard. Just a minor cleanup.
=> bp_common_defines.svh: remove no-op self-include

Makefile, Makefile.common
This change does the following:
1. adds the missing SHALLOW_SUB variable to Makefile.common
2. improves the "lite" make flow, e.g., `make prep_lite`, for the repo by creating a tools_lite target at the top and fixing the dependencies of prep_lite
=> Improve "lite" make flow

bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/syn/flist.vcs
For integration with systems which do not want our L2, we can use the unicore_lite. This is a version of the core without the L2, that directly exposes the mem_cmd/mem_resp bus.  For instance, manycore or LiteX integration can use this type of core
=> Breaking up unicore lite without L2

bp_fe/test/tb/bp_fe_icache/testbench.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cache/bp_me_cce_to_cache.sv
This change fixes a bug in bp_me_cce_to_cache module to disallow sending mem_resp messages until after the CLEAR_TAG routine completes in the command FSM. Prior to this, a valid memory command could arrive and trigger a memory response, regardless of the mem_cmd_ready_o status. So while consumption of the incoming mem_cmd obeyed handshaking rules, a valid command arriving before tag clear was done would trigger the sending of invalid memory response.
=> fix me_cce_to_cache bug - prevent sending responses until clear tag done

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
See issue #842 
I ran Verilator lint locally but it issued many hundreds of warnings on a default checkout so unclear if there's a better test to run.
=> Fix trivial syntax issue in bp_be_dcache.sv

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_top/src/v/bp_core.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/src/v/bp_unicore_lite.sv, docs/interface_specification.md
This PR adds distinct tag and data critical signals in the cache engine interface (the critical signal was previous implicitly data only). These signals can be used for snooping or early restart of the cache pipeline. Should be no functional change, just the new signals and the doc update
=> Add tag and data critical hints

bp_me/test/tb/bp_cce/Makefile.params, bp_top/test/tb/bp_tethered/Makefile.cfgs, bp_top/test/tb/bp_tethered/Makefile.params, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator
This PR adds a config variable in the bp_tethered testbench to detect whether the nbf file should load CCE ucode. The CCE ucode is only included in the nbf (and copied to the sim folder) if the config name contains the string "cce_ucode", as all standard configs with the ucode CCE do.
Note: a custom config that uses the ucode CCE by setting the cce_ucode field (https://github.com/black-parrot/black-parrot/blob/master/bp_common/src/include/bp_common_aviary_pkgdef.svh#L132) of the params struct to 1 will fail to load the ucode with this approach unless the config name can be set to include the string "cce_ucode".
Closes #840  
Also removes a deprecated variable in the makefiles related to CCE ucode file.
=> add config variable for ucode loading in nbf

bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
- Only do the division if we actually want to do it
- Specifically, don't write to zero on division instruction stored to zero
Fixes #832
=> Fix division to zero bug

bp_common/software/py/nbf.py, bp_common/src/include/bp_common_cfg_bus_pkgdef.svh, bp_top/src/v/bp_cfg.sv, docs/platform_guide.md
Non 64-bit alignment causes issues with external buses which don't support wrapping behavior. This patch increases the space allocated to registers within the CFG bus. It'll break external software, but the internal nbf loader has been updated to support this. Docs have been updated to reflect the changes
A future patch should create a header which unifies the NBF loader along with the RTL so that they stay in sync automatically. Further changes to these addresses before that QoL enhancement are discouraged.
=> Update CFG addresses

bp_be/test/tb/bp_be_dcache/testbench.sv, bp_fe/test/tb/bp_fe_icache/testbench.sv, bp_top/test/common/bp_nonsynth_cache_tracer.sv, bp_top/test/tb/bp_tethered/testbench.sv
The tracers should use the overridable "assoc_p" variables instead of "icache_assoc_p", etc. Otherwise there is a mismatch between the bound parameters and the instantiated module parameters in the case of targeted testbenches
=> Fix cache tracer associativity

bp_fe/src/v/bp_fe_pc_gen.sv
`pred_if1_r.btb`  and `pred_if1_r.bht` are always zero in this context, as the register which it takes input from contains only this:
https://github.com/black-parrot/black-parrot/blob/f5cbac361c8099b18b9b665c00bc02f691b654d4/bp_fe/src/v/bp_fe_pc_gen.sv#L88-L94
Based on suggestions from Dan and some trial-and-error, this PR introduces are what I believe to be the _correct_ values to use in the modified expressions. My reasoning for the changes is as follows.
- `btb_miss_ras` and `btb_miss_br` are checking on the RHS of the `|` for a mismatch in the selected pc of the first stage, which is why they use the `if1` value. However, on the LHS of that expression, it is presumably attempting to check whether the prediction of the preceding instruction came from the BTB, which would be the PC …
=> Fix usage of IF1 state in IF2 branch prediction fallback logic

bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_common/src/v/bsg_rom_param.v, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_host.sv
This PR adds a Verilog "ROM" containing the aviary information, allowing BP to query it with no hardware overhead. In silicon, this would either be a once-programmable ROM, flash, some configuration bits in HW, etc. This should let us write more portable tests which use libperch more flexibly
=> Adding aviary ROM

bp_be/syn/flist.vcs, bp_common/src/v/bsg_dff_sync_read.v, bp_fe/syn/flist.vcs, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_me/syn/flist.vcs, bp_top/syn/flist.vcs
This PR does a few things.
- The most important is the critical path fix in the UCE and LCE.  Currently, we stream out non-blocking requests (uc, wt, l2 amo) in a single cycle. This leads to a path from the cache AMO unit through the cache engine to routers, accelerators, etc.  Instead, this PR delays the output of the request by a single cycle and accepts a new request if the non-blocking request is sent out in the same cycle. In this way, we maintain 100% throughput for non-blocking requests, so there are no cycle-level performance implications.
- The second is adding a tag mem read register in the LCE. This is currently unused because the shadow tags are not needed by the CCE which maintains the true tags. However, I tested it and synthesis rips this unused register out anyway, so I …
=> Breaking critical uncached path in cache engines

bp_common/src/include/bp_common_cfg_bus_pkgdef.svh, bp_me/src/v/cache/bp_me_bedrock_register.sv, bp_top/src/v/bp_cfg.sv, bp_top/src/v/bp_clint_slice.sv, bp_top/src/v/bp_loopback.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/syn/flist.vcs, docs/bedrock_guide.md
- Converts the tile peripherals to single-beat stream in prep for future
- Adds bp_me_bedrock_register which acts as a Bedrock->GPIO converter. This makes things a little bit easier to connect low-performance peripherals to a tile. Can be expanded as needed for bursting requirements
Depends on #888
=> Adding bedrock register and stream peripherals

.gitlab-ci.yml, bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/tb/bp_be_dcache/testbench.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_fe/test/tb/bp_fe_icache/testbench.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_top/test/common/bp_nonsynth_cache_tracer.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR adds D$ operation to the scoreboard, so that cache misses do not block the pipeline. This is nice for performance, but necessary for non-idempotent remote atomic or uncached operations
=> Non-replay D$

bp_common/syn/v/bsg_mem_1r1w_sync.v, bp_common/syn/v/bsg_mem_1rw_sync.v, bp_common/syn/v/bsg_mem_1rw_sync_mask_write_bit.v, bp_common/syn/v/bsg_mem_1rw_sync_mask_write_byte.v, bp_common/syn/v/bsg_mem_2r1w_sync.v, bp_common/syn/v/bsg_mem_3r1w_sync.v, bp_top/test/tb/bp_tethered/Makefile.sv2v
#896 
Makefile.sv2v, adds common verilog files
The current SV2V flow does not substitute blackbox RAMs, leading to long runtimes and excessively long elaboration lists, causing issues in some tools.
none
No impact on PPA, some makefile complexity. 20m->1m bsg_sv2v runtime.
Manual inspection of output netlist.
none
=> Adding hardened stubs

bp_common/src/include/bp_common_bedrock_if.svh, bp_me/src/v/cce/bp_cce.sv, bp_me/src/v/cce/bp_cce_fsm.sv, bp_me/src/v/cce/bp_cce_inst_stall.sv, bp_me/src/v/cce/bp_cce_msg.sv, bp_me/src/v/cce/bp_cce_reg.sv, bp_me/src/v/cce/bp_cce_src_sel.sv, bp_me/src/v/cce/bp_cce_wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/dev/bp_me_cce_to_cache.sv, bp_me/src/v/network/bp_me_stream_pump_in.sv, bp_me/src/v/network/bp_me_stream_pump_out.sv, bp_me/src/v/network/bp_me_xbar_burst.sv, bp_me/src/v/network/bp_me_xbar_burst_bidir.sv, bp_me/src/v/network/bp_me_xbar_stream.sv, bp_me/src/v/network/bp_me_xbar_stream_bidir.sv, bp_me/syn/flist.vcs, bp_me/test/common/bp_cce_mmio_cfg_loader.sv, bp_me/test/common/bp_me_nonsynth_cce_tracer.sv, bp_me/test/tb/bp_cce/testbench.sv, bp_me/test/tb/bp_cce/wrapper.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/syn/flist.vcs, bp_top/test/tb/bp_tethered/testbench.sv
This PR updates the FSM CCE to use BedRock Stream on its memory ports.
For now, this is a draft for viewing the diffs.
=> update FSM CCE to use BedRock Stream on memory ports

bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR prevents non-replay D$ from appearing to break SC when stores commit before they are put in the write buffer. Figuring out a cleaner way to address this
=> Fixes for multicore cosimulation with a non-replay D$

bp_me/test/common/bp_nonsynth_dram.sv
AXI DRAM module, uncore.
Reasoning seen here: https://github.com/bespoke-silicon-group/basejump_stl/pull/480.
Depends on: https://github.com/bespoke-silicon-group/basejump_stl/pull/480.
May be minor PPA impact from crossing boundary before / after doing arithmetic, but AXI signals can easily be pipelined to mitigate this effect if necessary. AXI is not currently on any known critical paths.
Passes general regression with DRAM=axi switch.
External users demand more flexibility in address hashing.
=> Separating out hash function in bsg_cache_to_axi

.gitlab-ci.yml, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
Thanks for contributing to BlackParrot! Check out the CONTRIBUTING guide, if this is your first
time. A few details to check:
Does this PR address a BlackParrot GitHub issue? Link it here:
dpetrisko: https://github.com/black-parrot/black-parrot/issues/784
Module/tool/makefile/script in question.
bp_be_pipe_fma.v, Vivado, Zynq 7020
Why is this change required?
For devices/tools that do not do the necessary retiming automatically
Next steps, downstream modules affected, etc.
Once HardFloat changes are pulled, we can set manual latency distribution; otherwise unchanged.
[Ref](https://github.com/bsg-external/HardFloat/pull/8)
Potential impact of the change.
None as is
dpetrisko: expected frequency boost from 25->50MHz in FPGA. Minimal area impact in ASIC/FPGA and no performance impact.
Steps …
=> Parameterized manual retiming for Zynq 7020

.gitlab-ci.yml, bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_dcache_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/tb/bp_be_dcache/testbench.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/v/bsg_deff_reset.v, bp_top/src/v/bp_cacc_vdp.sv, bp_top/syn/flist.vcs, bp_top/test/tb/bp_tethered/testbench.sv
This is a minor refactor of the PTW, for clarity
PTW, D$, LSU
The current setup is confusing and error prone. Additionally, by not differentiating between PTW and regular loads, non-blocking loads are complicated, since the PTW miss may also be scoreboarded.
Additionally added a true miss signal to the $, which will allow users to differentiate between a miss and a fail. Lastly, this PR introduces a double edge FF (scary), which will be used in future work for posedge/negedge D$ handshakes.
No PPA impact, just clarity.
=> Minor refactor of PTW

bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_common/src/include/bp_common_rv64_csr_defines.svh, bp_fe/src/v/bp_fe_top.sv, bp_top/test/common/bp_nonsynth_cosim.sv
Converting to BSG_SIGN_EXTEND as shown in this PR: https://github.com/bespoke-silicon-group/basejump_stl/pull/474
This fixes vivado bugs which intermittently drop some of the bits of a sign extension
=> Converting to bsg_sign_extend

bp_me/src/v/network/bp_me_xbar_stream_buffered.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/syn/flist.vcs, bp_top/test/tb/bp_tethered/testbench.sv, bp_top/test/tb/bp_tethered/wrapper.sv
This PR adds a new module, bp_me_stream_xbar_buffered, which wraps the xbar with twofers to break timing paths.
This fixes the timing regression from #915, at the cost of additional buffers in the crossbar. 
The crossbars in bp_tile and bp_unicore_lite, notably the paths to/from the stream pumps.
While buffers are not functionally required, even for helpfulness, a medium-sized crossbar will require these fifos. Additionally, in the unicore these paths include I/O paths, which can be severely late-arriving.
Increased area and 2 additional cycles to L1 cache fill.
Normal regression, as this is not a functional change.
=> Adding buffered crossbar

.gitlab-ci.yml, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/tb/bp_tethered/testbench.sv
This fixes a potential issue where cosimulation buffers fill up and overflow. The case that could cause this is if there are a large number of nonblocking OOO operations such as integer divides or cache misses, several completed entries could enter the cosimulation fifo. If the FIFO is committing at 1 IPC, then it can only "catch up" to the processor on processor stalls. If there aren't any catchup cycles, eventually the fifo may overrun.
This PR makes the cosimulation clock much faster than the core clock, enable it to drain as soon as dependencies are met. Additionally, this provides additional safety in the context of multicore cosimulation.
Last, it provides a hook to wait on coherence operations to complete. This is essential for ordering commits of stores in the context of a …
=> Making cosimulation fifo asynchronous for faster draining

.gitlab-ci.yml, bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_complex.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/test/common/bp_nonsynth_if_verif.sv, bp_top/test/tb/bp_tethered/wrapper.sv
This PR adds hartid to unicore, allowing more than one unicore per system. Would have been nice in previous systems, but looking forward will be essential to multi-unicore systems.
Unicore
Would be nice to have a test configuration with multiple unicores, but not essential for this change.
Regular regressions suffice. Has been tested with multiple coordinate configurations.
=> Adding hartid to unicore

bp_me/src/v/lce/bp_lce_req.sv
Thanks for contributing to BlackParrot! Check out the CONTRIBUTING guide, if this is your first
time. A few details to check:
This PR adjusts the cache request valid register in the LCE Request module and tweaks the credit counting to prevent overwriting and dropping of uncached store requests.
Fixes #945
LCE Request
Functional bug fix
None
Newly added `mc_uc_store` test in[ bp-tests](https://github.com/black-parrot-sdk/bp-tests/tree/dev_mc_tests) exposes this bug, although the test still reports PASS. With LCE_TRACE_P=1 set, counting the number of uncached stores in the LCE trace file to the putchar address shows that ~25% of stores were dropped in a sequence of 100 consecutive stores. With fix applied, all stores are accounted for.
The added debug check should catch the issue in …
=> fix LCE uncached store overflow - #945

.gitlab-ci.yml, bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/tb/bp_be_dcache/flist.vcs, bp_be/test/tb/bp_be_dcache/testbench.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/include/bp_common_host_pkgdef.svh, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/tb/bp_fe_icache/flist.vcs, bp_fe/test/tb/bp_fe_icache/testbench.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/network/bp_me_burst_to_stream.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/common/bp_nonsynth_host.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR more elegantly addresses non-idempotency issues in the replay D$.  Misses should be sent non-speculatively and immediately be followed by hits. This is especially important for L2 atomics, where replaying the action can result in hung locks, etc. Our implementation creates a "late" port for the D$ which can inject the miss into the register file and clear the scoreboard asynchronously with the rest of the pipeline. 
D$ and cache engines
Moderate increase in complexity and mild performance boost as we scoreboard D$ misses instead of stalling independent instructions. There should be an average energy decrease as we're also reducing the number of SRAM reads in the D$, but that's a secondary bonus
Full regression and linux boot.
Builds on #938
=> Late writeback for the D$

bp_top/src/v/bp_unicore_lite.sv, docs/platform_guide.md
This PR changes the I/O logic in unicore lite to send non-local I/O requests outside of the unicore. This is useful for adding accelerators, coprocessors, etc.
=> Enables local off-core I/O in bp_unicore_lite

.gitlab-ci.yml, bp_me/src/v/cce/bp_cce_fsm.sv, bp_me/test/tb/bp_cce/Makefile.params, bp_top/test/tb/bp_tethered/Makefile.params, ci/me_regress.sh
Updating coherence protocol of the FSM CCE from MESI to MOESIF, with minor bug fix in cacc vdp accelerator that was exposed by the protocol update. Also bumping ucode CCE to use MOESIF by default.
ME and CACC VDP accelerator
ucode CCE supports full MOESIF protocol, bringing FSM CCE to parity.
Next steps, downstream modules affected, etc.
Regular CI
=> update FSM CCE to MOESIF protocol

bp_me/src/v/dev/bp_me_clint_slice.sv, bp_me/test/common/bp_me_nonsynth_dev_tracer.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/test/common/bp_nonsynth_host.sv, bp_top/test/tb/bp_tethered/Makefile.params, bp_top/test/tb/bp_tethered/flist.vcs, bp_top/test/tb/bp_tethered/testbench.sv
Add a ME device tracer module (CLINT, CFG, loopback, cce_to_mem). Module traces only the BedRock Stream cmd/resp interface.
Instantiate for CLINT in multicore and unicore, controlled by `dev_trace_p` parameter in testbench.
=> ME device tracer

bp_common/src/include/bp_common_aviary_defines.svh, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/dev/bp_me_bedrock_register.sv, bp_me/src/v/network/bp_me_stream_pump_in.sv, bp_me/src/v/network/bp_me_stream_pump_out.sv, bp_me/src/v/network/bp_me_stream_wraparound.sv
This change includes:
- cleanup / comment clarification in stream pumps
- small bug fix in bedrock register rd_not_wr logic (only used by assertion)
- fix CCE way group calculation for correctness in configs with differing L1 I$ and D$ organizations
- comment fix in UCE
=> Minor ME cleanup and CCE way group calculation fix

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv, bp_me/src/v/cce/bp_cce_dir.sv, bp_me/src/v/cce/bp_cce_fsm.sv, bp_me/src/v/cce/bp_cce_reg.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/dev/bp_me_bedrock_register.sv, bp_me/src/v/dev/bp_me_cce_to_cache.sv, bp_me/src/v/network/axi_fifo.sv, bp_me/src/v/network/bp_me_axil_master.sv, bp_me/test/common/bp_me_nonsynth_lce_tracer.sv, bp_me/test/common/bp_me_nonsynth_mock_lce.sv, bp_top/test/common/bp_nonsynth_nbf_loader.sv, bp_top/test/common/bp_nonsynth_watchdog.sv
This change adds a check to assertions to gate them on reset == 1 or X. This is useful for systems which bringup reset after a while (ASIC emulation). In these cases, spurious assertions may fire before reset has been raised for the first time
=> Adding reset_i X gate to assertions

bp_me/src/v/network/bp_me_axil_client.sv, bp_me/src/v/network/bp_me_axil_master.sv
Removing inferred latches from bp_me_axil_master and bp_me_axil_client. state_n didn't have a default value so it was becoming a latch.
fixes #972 
AXI master and client subcomponents
=> Fix inferred latches

.gitlab-ci.yml, bp_common/src/v/bsg_crossbar_control_locking_o_by_i.v, bp_me/src/v/network/bp_me_xbar_stream.sv, bp_top/syn/flist.vcs
This PR makes bp_me_xbar_stream into a true crossbar, rather than a glorified round robin arbiter. 
bp_me_xbar_stream
There is potential for deadlock if there are circular dependencies in the local crossbar. This can happen when an external device is writing to BP, while BP is polling the host. There are many ways to break this cycle, but preventing unnecessary blocking in this crossbar is low cost and provides nice guarantees for BP integrated in external systems
Need to modify xbar burst to also have this behavior.
Should have a minimal PPA impact. The data plane of the crossbar is unchanged, it's simply the 
https://github.com/bespoke-silicon-group/basejump_stl/pull/536
=> Make xbar stream a true crossbar

bp_common/src/v/bp_tlb.sv
This PR makes the TLB fall back to kilopages when gigapage support is not available. The old behavior was to drop the gigapage which is obviously not correct.
#973 
TLB
Should be no PPA impact, since the expression is not critical
Ran paging test before and after the change with and without gigapage support.  Adding this test to the regression before merging
=> Fixing behavior for zero gigapage support

bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_common/src/include/bp_common_rv64_csr_defines.svh, bp_top/test/common/bp_nonsynth_cosim.sv
This is a patch to fix: #967, #969, #970
Readonly CSRs must trap. That includes mhartid: https://groups.google.com/a/groups.riscv.org/g/isa-dev/c/gGRGSL2vOIo/m/R8SnwnpqBAAJ?utm_medium=email&utm_source=footer
There's also a fix so that FS is not dirtied during an illegal instruction trap.
There's also a patch to hardcode the low 2 bits of MEPC and SEPC
Tests for all in an incoming PR
=> Various CSR fixes

bp_fe/src/v/bp_fe_pc_gen.sv
Previously, the predictors would read garbage when the PC was the target of an override. This garbage would be used for the following prediction _and_ for the writeback to the BHT, trashing the row.
No open issue. Mentioned to Dan via Slack.
bp_fe_pc_gen
The BHT/BTB read happens in IF1. The read prediction data is for a prediction of the next instruction, i.e. the next one to enter IF1. There's no reason we would want to avoid the prediction due to the preceding instruction being originally mispredicted.
I suspect the original intent may have been to save power and skip the read for the invalidated IF1 PC on an override, but if I'm understanding correctly what it's actually doing is using that invalidated PC's entry for the real PC that follows since the BHT uses a bypass reg to latch the …
=> Read BTB and BHT even if processing an IF2 override

.gitlab-ci.yml, bp_be/src/include/bp_be_dcache_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_top/src/v/bp_cacc_vdp.sv, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/common/bp_nonsynth_if_verif.sv, bp_top/test/tb/bp_tethered/Makefile.cfgs, bp_top/test/tb/bp_tethered/Makefile.testlist, bp_top/test/tb/bp_tethered/testbench.sv, ci/single_core_atomics.sh
This PR enables L1 atomics for bp unicore. The L1 atomics were optional, but they are fairly low overhead and it is easier to integrate into vanilla RISC-V software so it makes a sensible default.
No issue
bp_be_dcache
https://github.com/black-parrot-sdk/bp-tests/pull/25
The major issue with L1 atomics is pressure on the 1rw rams in the dcache. Atomics both read and write the RAMs, so they don't fall into the normal paradigm of wbuf == dcache pipeline depth. One option is stalling wbuf entries until they are able to write back, but this complicates control logic. Instead, we detect an extra hazard condition when wbuf must write back or the request in TL will drop. This is absorbed by the normal replay mechanism.
=> Enabling L1 atomics for BP unicore

bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_top.sv, bp_common/src/include/bp_common_aviary_pkgdef.svh
This PR prevents FFLAGs instructions from proceeding while there are instructions pending that will write FCSR (fdiv, fqsrt). It also connects an erroneously disconnected infinite exception signal.
no issue raised
bp_be_pipe_long, bp_be_detector
Bug discovered by random verification
none
Potential performance regression if fflags are frequently checked. Not expected to cause issues
https://github.com/black-parrot-sdk/bp-tests/pull/24
=> Fix fflags hazards

.gitlab-ci.yml, bp_be/src/include/bp_be_dcache_defines.svh, bp_be/src/include/bp_be_dcache_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv, bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv, bp_be/test/tb/bp_be_dcache/testbench.sv, bp_be/test/tb/bp_be_dcache/trace_gen.py, bp_be/test/tb/bp_be_dcache/trace_script.py, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/v/bp_mmu.sv, bp_fe/src/v/bp_fe_top.sv, bp_top/src/v/bp_cacc_vdp.sv, ci/accelerator.sh
This PR adds misaligned instruction / load / store detection to BP. Upon detection the processor will trap as a normal exception.
#995 
bp_mmu, bp_be_pipe_mem, bp_fe_top
Trapping on misaligned instructions and load/stores is required for RISC-V compliance.
Some minor area overhead for the size decoding logic, but this is necessary for RISC-V compliance. Although performant programs should not use this, some low level code may.
https://github.com/black-parrot-sdk/bp-tests/pull/26
=> Misaligned Memory Access Detection

bp_be/test/tb/bp_be_dcache/testbench.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_fe/test/tb/bp_fe_icache/testbench.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_cce.sv, bp_me/src/v/cce/bp_cce_dir.sv, bp_me/src/v/cce/bp_cce_dir_lru_extract.sv, bp_me/src/v/cce/bp_cce_dir_segment.sv, bp_me/src/v/cce/bp_cce_dir_tag_checker.sv, bp_me/src/v/cce/bp_cce_fsm.sv, bp_me/src/v/cce/bp_cce_inst_predecode.sv, bp_me/src/v/cce/bp_cce_inst_ram.sv, bp_me/src/v/cce/bp_cce_msg.sv, bp_me/src/v/cce/bp_cce_src_sel.sv, bp_me/src/v/cce/bp_cce_wrapper.sv, bp_me/src/v/dev/bp_me_bedrock_register.sv, bp_me/src/v/dev/bp_me_loopback.sv, bp_me/test/common/bp_me_nonsynth_cce_tracer.sv, bp_me/test/common/bp_me_nonsynth_lce_tracer.sv, bp_me/test/common/bp_me_nonsynth_mock_lce.sv, bp_me/test/tb/bp_cce/testbench.sv, bp_me/test/tb/bp_cce/wrapper.sv, bp_top/src/v/bp_l2e_tile.sv, bp_top/src/v/bp_tile.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR adds a new param `bedrock_data_width` to the CCEs that controls the width of the LCE-CCE and CCE-MEM interface data widths. The data width of the LCE-CCE and CCE-MEM interface is required to be the same to eliminate unnecessary gearboxing inside the CCE. The physical networks carrying the messages can use an independently selected channel width, but are responsible for required gearboxing.
=> Add bedrock_data_width parameter to ME, update CCE

.gitlab-ci.yml, bp_be/src/v/bp_be_calculator/bp_be_nan_unbox.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_be/syn/flist.vcs, bp_top/syn/flist.vcs, bp_top/test/tb/bp_tethered/Makefile.testlist
Fixes nanboxing behavior in the FMA and FDIV units. This is (technically?) a regression since #1001 brought in this faulty nanboxing code. However, the nanboxing box existed before this as well.
#971
FPU
When doing a single precision operation, the operand will be converted into a NaN if the upper 32b of the raw value are not all 1. This is called nan-boxing in RISC-V terminology. We did attempt to nan-box, but we injected the incorrect NaN when unboxing. This caused us to accidentally garbage compute values instead of 
No PPA impact
=> Fixing nanboxing

bp_me/src/v/network/bp_me_axil_client.sv, bp_me/src/v/network/bp_me_axil_master.sv, bp_top/src/v/bp_axi_top.sv
This PR fixes the axi lite client for #1013. Writes are able to proceed at 100% throughput, but reads now take an additional cycle. Reads are much less common in our current AXI systems, but future enhancements could pipeline this as well by adding registers for the araddr and additional state
=> Fix to axil client

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv, bp_be/src/v/bp_be_top.sv, bp_common/src/include/bp_common_clint_pkgdef.svh, bp_me/src/v/dev/bp_me_clint_slice.sv, bp_top/src/v/bp_core.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_unicore_lite.sv
This PR brings S-mode external interrupt in BP. 
Mainly bp_be_csr.
1. s_external_interrupt.c from [bp-tests](https://github.com/black-parrot-sdk/bp-tests/pull/29)
2. Have tested it on Zedboard running Ethernet connection in Linux.
For now I set the S-mode interrupt address to 0x30_a000. Not sure if it really makes sense.
Also, I only considered single-core case, so I didn't do updates for modules like bp_tile, bp_core.
=> S-mode external interrupt

bp_me/src/v/dev/bp_me_clint_slice.sv, bp_top/src/v/bp_core_complex.sv, bp_top/src/v/bp_multicore.sv, bp_top/src/v/bp_tile.sv, bp_top/src/v/bp_tile_node.sv, bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_complex.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/syn/flist.vcs, bp_top/test/tb/bp_tethered/testbench.sv, bp_top/test/tb/bp_tethered/wrapper.sv
This PR adds a real time clock input to BP. In the testbench here, it is simply a downsampled clock. However, in a real system this could be connected a crystal oscillator etc. ~The increment is handled by a two stage synchronizer with edge detection~. The counter is gray-coded and synchronized before heading to the core clock domain
none
CLINT
Real systems often require RTC. The riscv platform spec additionally requires a 32 KHz real time clock (which we do not provide, but could).
FGPA wrappers need to update to generate the RTC (downsampled version). Any profilers that depend on an exact ratio must be adjusted.
=> Adding RTC

.gitlab-ci.yml, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, docs/platform_guide.md
This PR reduces the FMA latency from 5 to 4 cycles. 
none
FMA, hazard detection
This path was unnecessarily pessimistic. After #1001, there was a shorter path allocated for retiming the FPU. After confirming 3-cycle multiplication and 4-cycle FMA does not impact cycle time, we are reducing it to increase IPC for free.
none
PPA improvement, with fewer bypass paths, fewer flops and a shallower arithmetic retime
Synthesis in GF14 and TSMC28
=> Reducing FMA latency

.gitmodules, docs/testbench_guide.md
This PR bumps Surelog to https://github.com/chipsalliance/Surelog/commit/7772b03bbeb16888d4ac37e17568a690905794a7 and update related documentation to reflect the current build prerequisites.
N/A
tools
It updates outdated dependencies and documentation.
`black-parrot-sim` and `black-parrot-sdk` may need similar documentation updates.
No impact on functionalities.
Executing `make surelog; make -C bp_top/syn parse.surelog`.
N/A
=> Bump Surelog

bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/lce/bp_lce_req.sv
Two small tweaks to LCE logic:
- in LCE Request module, ready_o should not be raised if there are no available credits
- in LCE Command module, opportunistic stat memory read for writeback should occur when the last beat is being output, not when the last beat is consumed, to shorten the logic path for timing
=> small LCE logic tweaks

Makefile.tools
This PR modifies `Makefile.tools` to reflect the `$(CMAKE)` variable when Surelog is built.
Related to https://github.com/black-parrot/black-parrot-sim/issues/5
tools
Surelog failed to build where `cmake` is either CMake 2.x or not available.
None.
No impact on functionalities. It fixes build failures in certain environments.
Execute `make surelog CMAKE=cmake3` where `cmake` is not CMake 3. (ex. vanilla CentOS 7)
None.
=> Take $(CMAKE) into account for building Surelog

bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_lite.sv
This PR rearranges unicore and unicore lite so that most of the uncore is positioned in the unicore. 
none
bp_unicore/bp_unicore_lite
bp_unicore_lite is the minimal BP to integrate with external systems. Therefore, it only requires outgoing mem cmd/resp ports for I$ and D$. In this way, simply hooking these ports to a wishbone / AXI bus should be sufficient to bring up a new system. As well as setting the cfg_bus appropriately.
LiteX integration should be simplified, but needs to change. Other systems should be unaffected.
PPA should stay the same with this change. Rather than having two crossbars, we only have one of the same size. It should make it easier to integrate with other systems in the future, as well as with accelerators in the unicore complex
Normal regression
none
=> Rearranging Unicore/Unicore lite

bp_top/src/v/bp_unicore.sv, bp_top/src/v/bp_unicore_lite.sv
- Rearranges unicore/unicore_lite so that the crossbar is entirely in unicore (#1050)
This is a preparatory change for other rearrangements in the toplevel structure
=> Update dev to top_dev

bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/lce/bp_lce_fill.sv
This change fixes a bug in the LCE when cache block size is equal to cache fill width size. In this case, there is only a single fill packet so the first count input to the stream counter used to generate the proper fill index should be zero.
=> fix LCE fill when block size == fill width

.gitlab-ci.yml, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/v/bsg_dff_sync_read.v, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/lce/bp_lce_fill.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/src/v/bp_core.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/test/tb/bp_tethered/flist.vcs
The PR adds an explicit synchronization layer between the cache engine and memory system interfaces
bp_core, bp_unicore_lite, D$ / cache engines
The current implementation of explicitly extending handshakes is error-prone and counter-intuitive. Additionally, by clocking the cache different than the cache engine, we exposed half cycle paths to the rams. By moving the synchronization to the memory system, additional latency can be recaptured by explicit buffers which would exist for synchronization regardless. 
Although there is an increase in latches, this implementation is much safer. In the previous implementation, there was an implicit assumption that data and address would be held constant during a transaction, even though a state machine could change during the posedge/negedge of the …
=> Clean up Cache Engine Synchronization

bp_common/software/py/nbf.py, bp_common/src/include/bp_common_addr_pkgdef.svh, bp_me/src/v/dev/bp_me_cfg_slice.sv, bp_me/src/v/network/bp_me_addr_to_cce_id.sv, bp_top/src/v/bp_io_tile.sv, bp_top/src/v/bp_unicore.sv, bp_top/test/common/bp_nonsynth_perf.sv, bp_top/test/tb/bp_tethered/Makefile.cfgs, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator
This PR fixes bootrom configurations, by removing them entirely. That is, it makes BlackParrot always boot from bootrom. This is much less error prone than trying to manage several configurations of BlackParrot, some of which are only valid in certain environments, etc. There is a followup PR which will restore the ability to boot from DRAM, useful for some tethered environments
Depends on:
=> Fixing bootrom configurations

bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/v/bp_mmu.sv, bp_common/src/v/bsg_dff_sync_read.v, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/lce/bp_lce_fill.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/src/v/bp_core.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/test/tb/bp_tethered/flist.vcs, docs/platform_guide.md
- Reduces FMA latency (and mul) #1036 
- Cleans up cache interface from half cycle paths #1070 
- Latches PTW info to be a bit safer and critical path free
=> Update dev to be_dev

bp_be/syn/flist.vcs, bp_common/src/v/bsg_mem_1r1w_sync.v, bp_common/src/v/bsg_mem_1r1w_sync_synth.v, bp_fe/src/v/bp_fe_bht.sv, bp_fe/src/v/bp_fe_btb.sv, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/syn/flist.vcs, bp_me/syn/flist.vcs, bp_top/syn/flist.vcs
- Fixes branch prediction bug causing unnecessary read disables #984 
- Reduces critical path from predictor to large memories by leveraging hardened rams
=> Update dev to fe_dev

bp_me/test/common/bp_me_nonsynth_cache.sv, bp_me/test/common/bp_me_nonsynth_cache_tag_lookup.sv, ci/me_regress.sh
Fixes #1086 
Root cause was implementation of the nonsynth cache used in the ME testbench. Uncached stores targeting valid cache blocks were not self-invalidating the block, causing the store to get lost if targeted by following cacheable load. Bug is only present in the ME testbench, not in a real BP system.
=> Fix nonsynth cache UC store hit bug

bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_me/test/common/bp_me_nonsynth_cache.sv, bp_me/test/tb/bp_cce/test_gen.py, bp_me/test/tb/bp_cce/trace_gen.py, bp_top/test/tb/bp_tethered/Makefile.cfgs, ci/multicore.sh
This PR makes some small tweaks to testing and config related things for ME and multicore:
- refactor ME trace replay generation
- set L2 banks to 2 (default) for multicore configs up to 8 cores
- adds mc_lrsc_add test to multicore regressions
- refactors the NCPU computation in the top testbench to remove the need to keep the core per config list synchronized with the BP configs listing
=> Testbench and config cleanup for ME/multicore

bp_common/src/v/bsg_crossbar_control_locking_o_by_i.v
This PR fixes a bug in the locking crossbar control module.
The locking crossbar control module locks an input port for an output port if the input port is granted access to the output port until the input port completes streaming data through to that output port. The valid signal for every output port currently contains information if the output port has valid requestors from any of the input ports but does not contain any information about which input port has locked arbitration. It is possible that this creates a situation where input ports that haven't locked the arbiter can access the output port. The PR attempts to correct this.
The fix is to AND the output request mask with the information about which input has locked the arbiter.
There is no active issue that this PR addresses …
=> Crossbar Control Locking Bug

bp_be/src/v/bp_be_checker/bp_be_director.sv
This is a minor fix to the reset sequencing. Currently, when unfreezing under reset, there can be x-propagation as the dispatch packet / pipeline has not been cleared yet and the unfreeze packet expects the pipeline to be clear. This fix allows this sequence and freeze/reset can be asserted either way
=> Fix unfreeze under reset sequence

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_common/src/include/bp_common_core_pkgdef.svh, bp_fe/src/v/bp_fe_top.sv
This PR fixes the handling of misaligned instructions. Originally, we would raise a misaligned exception upon fetching a misaligned instruction. However, the correct spec behavior is to actually raise the exception on the instruction which causes the misalignment (i.e. the branch).
#216 
FE-BE interface (danger zone), and exception pipelines.
To comply with the privileged spec:
When we implement compressed instructions this check must be disabled entirely
No PPA impact, higher compliance.
Run with: https://github.com/black-parrot-sdk/bp-tests/pull/32 to verify that trap is taken as expected
=> Fixing misaligned instruction handling (should be in backend)

.github/PULL_REQUEST_TEMPLATE.md, .gitlab-ci.yml, bp_be/src/v/bp_be_calculator/bp_be_nan_unbox.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv, bp_common/software/py/nbf.py, bp_fe/src/v/bp_fe_btb.sv, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/tb/bp_tethered/Makefile.params, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator
Thanks for contributing to BlackParrot! Check out the CONTRIBUTING guide, if this is your first
time. A few details to check:
This PR addresses issues identified while bringing up an alternate FPGA setup using vivado+xsim.
None
NBF generation, and code in the BP backend
- XSIM cannot handle inferred struct muxing
- NBF may be required to clear zeros from memory in some setups
- NBF should use 32b requests for 32b config registers within BP for alignment purposes (Ucode is still 64b aligned)
None
No PPA impact
Build with XSIM and run standard regression on VCS (XSIM still doesn't fully simulate due to DPI calls)
None
=> Fixes for XSIM and NBF

bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
Same deal as #1104, but now in the scheduler when detecting register write collisions. The "true" instruction decode had the same issue as the pre-decode.
I don't see other instances of this in the scheduler module. The `iwb_v` and `fwb_v` signals are only used for scoreboard hazard detection as far as I can tell. My test cases suggest this is the last instance of unnecessary issue delays, but I can't guarantee there aren't other cases where the decoded instruction was used by mistake.
=> Mask WAW hazards when issuing exceptions

bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
This PR fixes a timing loop in the instruction scheduler and clarifies vaddr injection by gathering it from the instruction decoder and system pipe and putting it in the scheduler.
None
Scheduler and instruction decoder
Fixes timing loop caused by #1105 
None
Minimal PPA. Moves multiplexer in retirement to scheduler
Standard regression as well as check_loops and check_design
None
=> Fixing timing loop and clarifying vaddr injection

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_if_verif.sv, bp_top/test/common/dromajo_cosim.cpp
This PR adds optional support for hardware mulh. We implement this as an iterative multiplier due to large hardware overheads for a rarely used feature.
None, but general RISC-V compliance
Iterative multiplication pipe
Although this feature is rarely used, it's required for architectural compliance.
Other changes were already merged 
No impact for non-parameterized version. Unmeasured impact for iterative multiplier itself
RISC-V mulh tests
Supercedes https://github.com/black-parrot/black-parrot/pull/1061
=> Support MULH

bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_defines.svh
Currently unused and defaults to disabled.
Looking for this to go in before the main PR.
Precursor to #1098.
=> Introduce compressed_support_p config parameter

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
This PR lets the wbuf entry in the D$ flow through, rather than be delayed.
None
dcache wbuf
This was a performance regression introduced by #940, where the wbuf would wait for a cycle to sync up to the posedge. Since we moved the wbuf to the negedge, this was causing a full-cycle delay where there was only a half-cycle delay before.
None
No PPA impact, since we had data path signals flowing through, even though control signals were stifled.
Looking at specific ST-ST-LD patterns on coremark waveform
None
=> Fix accidental wbuf delay, causing data mem hazards

bp_fe/src/include/bp_fe_defines.svh, bp_fe/src/include/bp_fe_pc_gen_pkgdef.svh, bp_fe/src/include/bp_fe_pkg.sv, bp_fe/src/v/bp_fe_instr_scan.sv, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/src/v/bp_fe_ras.sv, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_branch_profiler.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR cleans up the pc_gen module of the frontend. Specifically, we're correcting metadata propagation and clarifying the pipeline flow to that fewer mistakes can be make about what data comes from where
#966  #987 #884 
pc_gen
The old pc_gen metadata scheme was an amalgamation of site and target information travelling along the pipeline. As we send metadata long with targets, it only makes sense to store that same metadata alongside of the target itself, rather than manually realigning in IF2. When reworking this new scheme, several performance bugs were discovered that caused incorrect behavior in degenerate cases. These bugs have also been fixed as part of this changeset. Lastly, the issues found by @WasabiFan are included as well.
The bugs revolved around losing the metadata …
=> Minor bugfixes and cleanup for pc_gen

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/common/bp_fe_nonsynth_icache_tracer.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_me/test/common/bp_me_nonsynth_cache.sv, bp_me/test/tb/bp_cce/testbench.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/src/v/bp_core_lite.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR updates cache_req_yumi to cache_req_ready. This simplifies the control scheme and allows the more critical cache paths to depend on future values of the ready signal.
None
I$/D$/XCE
While not a critical path itself, relying on the cache_req_yumi signal generates circular paths that can influence the control signals of large SRAMs in blocking caches
None
This is a generally noncontroversial change which may decrease paths at the cost of a trivial number of AND gates
Standard regressions
None
=> Update cache_req_yumi to cache_req_ready

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_checker/bp_be_director.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_defines.svh, bp_common/src/include/bp_common_core_if.svh, bp_common/src/include/bp_common_rv64_csr_defines.svh, bp_common/syn/Makefile.vcs, bp_fe/src/include/bp_fe_defines.svh, bp_fe/src/v/bp_fe_bht.sv, bp_fe/src/v/bp_fe_btb.sv, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/src/v/bp_fe_realigner.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/common/bp_fe_nonsynth_pc_gen_tracer.sv, bp_top/test/common/bp_nonsynth_branch_profiler.sv, bp_top/test/tb/bp_tethered/Makefile.testlist, bp_top/test/tb/bp_tethered/testbench.sv
This PR is the new revision of #986. It introduces support for executing 32-bit instructions aligned to an arbitrary 16-bit boundary. It does not widen or otherwise alter the instruction cache output; rather, it performs successive fetches and synthesizes the results via a new "realigner" component.
The key changes from the previous PR are as follows:
- Branch prediction metadata is now indexed by the aligned address of the second (upper) half of an instruction rather than the first (lower) half
- As a result, I've removed a bunch of state previously used to carry over this information
- Modified and narrowed the I/O interface between the PC gen module and the overall frontend
Note: Dan and I had previously discussed moving the realigner out of `pc_gen`. I took a deep dive on this …
=>  Support 32-bit instructions aligned to 16 bits (IALIGN=16), take two

bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/test/tb/bp_tethered/testbench.sv
bp_be_dcache ready_o operates via a ready_and handshake, and therefore this PR updates the signal to ready_and as per the style guide and modifies all instantiations of bp_be_dcache to use the updated naming convention.
None
BE, Top
Clarification of interface usage, more in line with existing style guide.
Verilator successfully built, no functional differences
=> Fixes ready handshake naming for bp_be_dcache

bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_top.sv, bp_fe/src/v/bp_fe_top.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/test/common/bp_nonsynth_core_profiler.sv, bp_top/test/tb/bp_tethered/testbench.sv
Renames fe_queue_ready_o signal to fe_queue_ready_and_o as the signal is used in a way consistent with the rv->& interface.
None
BE, FE, Top
Clarifies usage of the ready signal from bp_be_issue_queue and makes the interface more consistent with the style guide.
Built with Verilator with no issue, no functional changes so only linting required.
We see that it is rv->& from its [usage within the bp_be_issue_queue module](https://github.com/black-parrot/black-parrot/blob/master/bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv#L49) as well as the [generation of the ready signal](https://github.com/black-parrot/black-parrot/blob/master/bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv#L119). It can be noted that clr is directed from a signal labelled as valid, but it does not represent a …
=> Changes fe_queue_ready_o signal to ready_and interface

bp_common/src/v/bp_tlb.sv, bp_fe/src/v/bp_fe_controller.sv, bp_me/test/common/bp_nonsynth_dram.sv
This PR fixes 2 timing loops introduced by #1130, one in the TLB and one in the FE controller.
None; hotfix
FE and TLBs
Timing loops cause degenerate behaviors in CAD tools, especially FPGAs which may infer latches.
Synthesis is now clean
=> Hotfix for accidental timing loops

.gitlab-ci.yml, Makefile, bp_common/syn/Makefile.common, bp_common/syn/Makefile.vcs, bp_common/syn/Makefile.yosys, bp_common/syn/tcl/yosys_synth.tcl, bp_top/syn/Makefile, bp_top/test/tb/bp_tethered/Makefile.sv2v, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.yosys, ci/yosys.sh
This PR adds yosys synthesis and simulation. Make sure to update black-parrot-tools to take advantage of this flow
None
Adds Makefile infrastructure
yosys is a FOSS toolchain for synthesizing and sky130 is an open-source PDK we can synthesize with. This is the easiest way to get started with ASIC BP. 
This flow relies on bsg_sv2v which needs a Synopsys DC license. We would like to avoid this commercial requirement in the future.
None
Standard regression with the sv2v and yosys outputs
None
=> Adding yosys synthesis and simulation

bp_be/src/v/bp_be_checker/bp_be_expander.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_rv64_instr_defines.svh, bp_fe/src/include/bp_fe_pc_gen_pkgdef.svh, bp_fe/src/v/bp_fe_instr_scan.sv, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/src/v/bp_fe_realigner.sv, bp_fe/src/v/bp_fe_top.sv, bp_top/syn/flist.vcs
This PR adds compressed extension 'C' support to BlackParrot
Generally unhappiness with lack of C support.
FE instruction scanning and BE instruction issuing
This extension is required by the 'A22' RISC-V profile, meaning that general purpose Linux distributions will require it in the future.
There are potential new timing paths in FE and impact to performance in the worst and average cases. Branching to a misaligned instruction has an additional cycle of latency, which can degenerate for a mixed set.
Boots Linux and runs Caremark at <1% performance penalty
#1098 provided the baseline for this work
=> Adding Compressed Extension Support

bp_common/syn/Makefile.verilator
Addresses: https://github.com/black-parrot/black-parrot/issues/789
Just realised in one of my own projects that assertions need to be enabled with the `--assert` flag before they work in Verilator.
https://veripool.org/guide/latest/exe_verilator.html
Just place a little `assert(0);` in some `initial` blog.
For example for the `tire_kick` I get this without `--assert` flag:
```
Hello World!
[CORE0 FSH] PASS
All cores finished! Terminating...
```
With  `--assert` flag I get this:
```
Hello World!
[CORE0 FSH] PASS
[25866000] %Error: bp_nonsynth_host.sv:184: Assertion failed in testbench.testbench.host: 'assert' failed.
```
Of course don't forget to `make clean` in between.
=> Enable assertions

.gitlab-ci.yml, bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/syn/flist.vcs, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/syn/flist.vcs, bp_fe/test/common/bp_fe_nonsynth_pc_gen_tracer.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/dev/bp_me_cache_slice.sv, bp_me/src/v/dev/bp_me_cce_to_cache.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/network/bp_me_stream_gearbox.sv, bp_me/src/v/network/bp_me_stream_pump_control.sv, bp_me/src/v/network/bp_me_stream_to_wormhole.sv, bp_me/syn/flist.vcs, bp_top/src/v/bp_io_tile.sv, bp_top/src/v/bp_sacc_scratchpad.sv, bp_top/src/v/bp_sacc_vdp.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR fixes two bugs from #1169 and #1170. First, it eliminates a dependence on the tag_mem_pkt during upgrades in the cache. Second, it adds a buffer in the L2 cache slice to eliminate a deadlock occurring during a write back sequence to the same cache bank 
Stream pumps
None
=> Bugfix for critical word stream pump

bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_if_verif.sv
This PR adds support for 2bit per iteration IDIV and FDIV. This is configurable so that small configurations can ignore it, but performant configurations can leverage it.
#1138 
Long latency pipe
Most workloads do not care about IDIV/FDIV performance. But some do, and for those there's no getting around it
None
PPA and performance increase on large configurations, no change on smaller configurations
None
None
=> 2bit IDIV and FDIV

.gitlab-ci.yml, bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_me/src/v/dev/bp_me_cce_to_cache.sv, bp_me/test/common/bp_nonsynth_dram.sv, bp_me/test/common/bp_nonsynth_mem.sv, bp_top/test/common/bp_nonsynth_if_verif.sv, ci/weird_config.sh
This PR adds support for 64kB caches. While this would likely impact critical path, it is a configuration which makes sense for some performance-focused applications
#853 
Caches and fill path
User requests
None
Minimal, since it's a non-default option
None
=> Adding 1kB cache line megaparrot configuration

.gitignore, bp_be/syn/Makefile, bp_be/test/tb/bp_be_dcache/Makefile.xcelium, bp_common/syn/Makefile.xcelium, bp_fe/syn/Makefile, bp_fe/test/tb/bp_fe_icache/Makefile.xcelium, bp_me/syn/Makefile, bp_me/test/tb/bp_cce/Makefile.xcelium, bp_top/syn/Makefile, bp_top/test/common/bp_nonsynth_branch_profiler.sv, bp_top/test/common/bp_nonsynth_core_profiler.sv, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/common/bp_nonsynth_pc_profiler.sv, bp_top/test/tb/bp_tethered/Makefile.xcelium, bp_top/test/tb/bp_tethered/xcelium_dump.tcl
This PR adds support for xcelium simulation. It's preliminary and does not support many TB features, but should allow users to run standard regressions.
None
Simulation makefiles
Some shops / labs are Cadence only and we don't want to exclude them
None
No design impact
Smoke test of a few programs. Users can raise alarms if certain flows are unsupported
None
=> Adding Xcelium support

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_director.sv, bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_top.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_defines.svh, bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_top/test/tb/bp_tethered/testbench.sv
This PR adds an optional, secondary "catchup" ALU which is used to unblock the pipeline in the case of a load->int/load->branch dependency. With perfect branch prediction, this eliminates all load-use stalls in the pipeline.
None
BE decoder and hazard detection
Performance enhancement, mainly Coremark
None
PPA has not been analyzed for this feature, but it is unlikely to impact critical path. Area is estimated to be ~2% based on other ALU size.
Standard regression and Linux Boot
None
=> Catchup ALU

.gitlab-ci.yml, bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/syn/Makefile.vcs, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/dev/bp_me_bedrock_register.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_me/test/tb/bp_cce/testbench.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/src/v/bp_core_lite.sv, bp_top/src/v/bp_unicore_lite.sv
This PR adds a fifo to local cache engines, which more elegantly handles back to back non-blocking requests. 
Related to #1183 
UCE, LCE, D$
Before, negedge synchronization could cause a ready signal from the cache engine to happen in the second half of a cycle. This could cause an error if the core pipeline inspects the signal in the first half of the cycle.
None
Slight area increase in cache engines, but reduction in cache size by getting rid of enables.
Standard regression and linux boot.
None
=> Adding fifo to cache engines

.gitlab-ci.yml, bp_be/src/include/bp_be_dcache_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_fe/src/v/bp_fe_icache.sv, bp_fe/src/v/bp_fe_top.sv, bp_fe/test/common/bp_fe_nonsynth_icache_tracer.sv, bp_fe/test/tb/bp_fe_icache/wrapper.sv, bp_me/src/v/cce/bp_uce.sv, bp_me/src/v/lce/bp_lce.sv, bp_me/src/v/lce/bp_lce_cmd.sv, bp_me/src/v/lce/bp_lce_req.sv, bp_me/test/common/bp_me_nonsynth_cache.sv, bp_me/test/tb/bp_cce/testbench.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/src/v/bp_core_lite.sv, bp_top/src/v/bp_core_minimal.sv, bp_top/src/v/bp_unicore_lite.sv, bp_top/test/common/bp_nonsynth_cosim.sv, docs/interface_specification.md
This PR adds the capability to hit under a single miss in the D$. This gives a mild performance increase on workloads which are stalling on head of line for miss. The true benefit is that this sets us up for a future fully nonblocking implementation without any changes to the surrounding pipeline structure.
None
D$/UCE/Memory System
For an in-order core, a blocking D$ can present a significant bottleneck on performance as a bypassing cache will then only allow average 3 instructions (assuming 1/4 memory operations) after a miss. A hit-under-miss cache will allow up to the next dependency.
The cache engine interface terminology has changed slightly, so minor updates to downstream blocks are required.
Verified with synthesis to have <1% area impact
Linux boot and manual waveform inspection …
=> Hit under single miss for D$

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_dcache_pkgdef.svh, bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_checker/bp_be_director.sv, bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_common/src/include/bp_common_cache_engine_pkgdef.svh, bp_common/src/include/bp_common_core_pkgdef.svh, bp_fe/src/include/bp_fe_icache_pkgdef.svh, bp_fe/src/v/bp_fe_controller.sv, bp_fe/src/v/bp_fe_icache.sv, bp_me/src/v/cce/bp_uce.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/test/common/bp_nonsynth_cache_tracer.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR edits the fence.i implementation to eschew replays. This leads a more robust and less special-casey implementation.
None
FE-BE interface, BE memory pipeline.
Before the flow for a fence.i was
- check dirty bit in cache
- flush d$
- replay fencei
- send I$ invalidation
- continue fetching
With the new flow, I$ invalidation will happen in parallel with D$ clear. This has better performance and energy efficiency (since we won't continue fetching during this time).
None
No PPA change
None
=> Refactor fencei for robustness

bp_be/syn/flist.vcs, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_defines.svh, bp_common/src/include/bp_common_aviary_pkgdef.svh, bp_fe/syn/flist.vcs, bp_me/src/v/dev/bp_me_cache_controller.sv, bp_me/src/v/dev/bp_me_cache_slice.sv, bp_me/src/v/dev/bp_me_cce_to_cache.sv, bp_me/src/v/dev/bp_me_dram_hash_decode.sv, bp_me/src/v/dev/bp_me_dram_hash_encode.sv, bp_me/test/common/bp_nonsynth_dram.sv, bp_me/test/common/bp_nonsynth_mem.sv, bp_me/test/tb/bp_cce/flist.vcs, bp_top/src/v/bp_core.sv, bp_top/src/v/bp_l2e_tile.sv, bp_top/src/v/bp_l2e_tile_node.sv, bp_top/src/v/bp_multicore.sv, bp_top/src/v/bp_processor.sv, bp_top/src/v/bp_unicore.sv, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_if_verif.sv, bp_top/test/tb/bp_tethered/testbench.sv, bp_top/test/tb/bp_tethered/wrapper.sv
This PR reworks the L2 banking strategy to increase bandwidth linearly with number of banks. It also parameterizes the internal networking IDs to make it easier to add peripherals within a BlackParrot tile.
None
L2 cache controller and unicore/core toplevels
The current banking scheme allows for MLP on cache misses to independent banks, but the serialization in the crossbar means that simultaneous requests need to wait even if a single bank is idle. We want to unlock scalable bandwidth for attached accelerators.
(Also, the current code is confusing as to what the requirements are to add a new internal master/client to the crossbar. With these changes, there are only a few lines needed to add new master/client attached accelerators).
None
Saturation bandwidth now scales linearly with the …
=> L2 banking rework

bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_sys.sv, bp_be/src/v/bp_be_checker/bp_be_detector.sv, bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_be/src/v/bp_be_checker/bp_be_scheduler.sv, bp_be/src/v/bp_be_checker/bp_be_scoreboard.sv, bp_be/src/v/bp_be_dcache/bp_be_dcache.sv, bp_be/src/v/bp_be_top.sv, bp_be/test/tb/bp_be_dcache/testbench.sv, bp_be/test/tb/bp_be_dcache/wrapper.sv, bp_top/src/v/bp_cacc_vdp.sv, bp_top/test/common/bp_nonsynth_core_profiler.sv, bp_top/test/common/bp_nonsynth_cosim.sv, bp_top/test/tb/bp_tethered/testbench.sv
This PR fixes the late writeback capability of the pipeline to support multiple asynchronous functional units. In order to avoid adding ports to the register file or requiring backpressure on the memory system, we inject writebacks directly into the completion pipeline. From there, normal forwarding paths can handle the dependencies.
None
calculator / pipe_long / pipe_mem
For adding multiple late writers, a round robin is desired. However, our memory pipe relies on a nonblocking writeback pipeline. To avoid multiporting the register file or implementing a reorder buffer, we repurpose the normal completion pipeline. This is the TINY solution
None
PPA unaffected confirmed by synthesis
Normal regression with manual inspection of write backs
None
=> Fix late writeback for scalability

bp_be/src/include/bp_be_defines.svh, bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv, bp_be/src/v/bp_be_calculator/bp_be_ptw.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_defines.svh, bp_common/src/include/bp_common_core_if.svh, bp_common/src/v/bp_mmu.sv, bp_common/src/v/bp_tlb.sv, bp_fe/src/v/bp_fe_controller.sv, bp_fe/src/v/bp_fe_top.sv, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_vm_tracer.sv, bp_top/test/tb/bp_tethered/Makefile.testlist, bp_top/test/tb/bp_tethered/testbench.sv
This PR adds parametrizable megapage support to BlackParrot.
None
MMU / TLB
Megapages are predominately used in user space Linux applications such as SPEC benchmarks. Leveraging them grants a larger effective TLB capacity
None
No critical path increase when parameterized out
Linux boot and synthesis
=> Adding megapage support

.gitlab-ci.yml, bp_me/src/include/bp_me_cce_inst_pkgdef.svh, bp_me/src/v/cce/bp_cce_fsm.sv, bp_me/src/v/cce/bp_cce_inst_decode.sv, bp_me/src/v/cce/bp_cce_msg.sv
This change modifies the CCE to properly handle writebacks and mem_rev responses to writebacks and uncached store operations. For mem_fwd writes, the payload.uncached bit is set only for uncached stores being issued by the CCE. All writebacks sent to L2/memory have the payload.uncached bit cleared to indicate that no response to the LCE will be required when the mem_rev returns.
CCE
This supports the removal of the UC operation types from the mem_fwd/rev networks.
Standard CI runs.
=> Implement correct handling of writebacks and uncached stores in CCE

Makefile.common, bp_be/src/include/bp_be_ctl_pkgdef.svh, bp_be/src/v/bp_be_calculator/bp_be_csr.sv, bp_be/src/v/bp_be_calculator/bp_be_int_unbox.sv, bp_be/src/v/bp_be_calculator/bp_be_pipe_int.sv, bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv, bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_common/src/include/bp_common_aviary_defines.svh, bp_common/src/include/bp_common_host_pkgdef.svh, bp_common/src/include/bp_common_rv64_instr_defines.svh, bp_top/syn/flist.vcs, bp_top/test/common/bp_nonsynth_host.sv, bp_top/test/tb/bp_tethered/Makefile.testlist, bp_top/test/tb/bp_tethered/Makefile.vcs, bp_top/test/tb/bp_tethered/Makefile.verilator, bp_top/test/tb/bp_tethered/Makefile.xcelium
This PR adds the newly frozen bit manipulation extension to BlackParrot. B includes Zba, Zbb and Zbs (but not Zbc), and is predicted to be required for future standard versions of Linux.
None
Integer execution units
This is expected to be a standard feature and can help with many 32b and embedded systems use-cases.
None
Less than 1% area impact. Performance impact TBD.
added riscv-arch-test compliance and spike co-simulation. Additionally, still boots Linux. Critical path unchanged and minimal area impact.
None
=> Adding Zba, Zbb, Zbs

bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh, bp_fe/src/include/bp_fe_defines.svh, bp_fe/src/v/bp_fe_pc_gen.sv, bp_fe/src/v/bp_fe_ras.sv
This PR adds RAS checkpointing inspired by Patt '97.
None
FE
The previous RAS checkpointing strategy suffered from pop-push-pop-restore problem, which is exacerbated when fetching ahead more aggressively.
None
<0.1% area impact
Standard regression and cycle-level debugging
None
=> RAS checkpointing enhancement

bp_common/syn/Makefile.verilator, bp_top/test/tb/bp_tethered/testbench.sv
This change re-enables waveform dumping for Verilator simulations by adding a define of VERILATOR_TRACE to the verilated executable build that is visible to the testbench.
=> re-enable waveform dumping when simulating with Verilator

bp_me/src/v/dev/bp_me_dram_hash_decode.sv, bp_me/src/v/dev/bp_me_dram_hash_encode.sv
This PR does two things:
1. fixes the L2/DRAM hashing to account for fields that may have 0-width (CCE, slice, bank, and set indices)
2. prevents aliasing of blocks outside the L2 capacity
The purpose of the hash function is to distribute the L2 blocks evenly across the L2 slices/banks. This algorithm distributes blocks first to CCEs, then across slices and across banks (i.e., slice 0, bank 0 - slice 1, bank 0 - slice 0, bank 1 - slice 1, bank 0, etc.).
By definition (at least for POT number of CCEs), this algorithm guarantees that if there are N total sets across all L2s, then blocks [0, N) will remap to the same range and not alias outside the the L2 capacity.
Number of CCEs can be NPOT, but number of slices, banks, and sets must be POT >= 1.
=> rework dram hash encode/decode to account for 0-width fields

bp_fe/src/v/bp_fe_top.sv
Adds a couple missing signal declarations in FE Top.
Should be merge squashed.
=> Add missing signal declarations in FE
