black-parrot/black-parrot

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v

add data gating the int alu, multiplier, and mem in the calculator top
clock period           2.5ns
performance                     power(tower)                       cell area
baseline(post synth)                2.5ns                                  1.2628e5 uW                       1283284 um^2
data gating(post synth)           2.5ns                                  1.2563e5 uW                       1284138 um^2
difference                                 0%                                       -0.5%                                   +0.066%

adding data gating for calculator top

---

bp_be/src/v/bp_be_calculator/bp_be_regfile.v

We have hardened register files in the calculator module.
The frequency changed from 303.03Mhz to 302.85Mhz.
The power went down ~6%.
The area went down ~4%.

BE Harden Regfile

---

bp_fe/src/v/bp_fe_cce_lce_cmd.v
bp_fe/src/v/bp_fe_cce_lce_data_cmd.v
bp_fe/src/v/bp_fe_icache.v
bp_fe/src/v/bp_fe_icache_lru_decode.v
bp_fe/src/v/bp_fe_icache_lru_encode.v
bp_fe/src/v/bp_fe_itlb.v
bp_fe/src/v/bp_fe_lce.v
bp_fe/src/v/bp_fe_lce_cce_req.v
bp_fe/src/v/bp_fe_lce_lce_tr_resp_in.v
bp_fe/syn/flist.vcs

Resizing of I-cache. 55% decrease on FE area with no impact on performance.

Pparrot icache refactor

---

bp_me/test/common/bp_mem_dramsim2.v
bp_me/test/common/dramsim2_wrapper.cpp

Fixes for DRAMSim2, which fix an issue with requests being discarded if the DRAM ctl FIFOs were full

Hotfix for DRAMSim2

---

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v
bp_be/src/v/bp_be_top.v
bp_be/test/common/bp_be_nonsynth_tracer.v
bp_common/src/include/bp_common_aviary_defines.vh
bp_me/src/v/network/bp_me_lce_data_cmd_router.v
bp_me/src/v/network/bp_me_lce_data_resp_router.v
bp_me/src/v/network/bp_me_tile_router.v
bp_top/src/v/bp_core.v
bp_top/src/v/bp_tile.v
bp_top/src/v/bp_top.v
bp_top/syn/flist.vcs
bp_top/syn/flist.verilator
bp_top/test/tb/bp_top_trace_demo/wrapper.v

This is an attempt to reorganize BlackParrot as in #123 
Initially, I'm tiling with full networks and will replace with wormhole version of data_cmd and data_resp once this version passes RTL.
Currently, this is broken. There are Xs propagating. I will dig into it when I get a chance, but let me know if anything looks weird to you in bp_tile.v or bp_top_tiled.v

Attempt at tiling BP

---

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce.v
bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_cmd.v
bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_data_cmd.v
bp_fe/src/v/bp_fe_lce.v
bp_fe/src/v/bp_fe_lce_cmd.v
bp_fe/src/v/bp_fe_lce_data_cmd.v
bp_me/src/v/network/bp_me_network_pkt_encode_data_cmd.v
bp_me/src/v/network/bp_me_network_pkt_encode_data_resp.v
bp_top/src/v/bp_tile.v
bp_top/src/v/bp_top.v
bp_top/test/tb/bp_top_trace_demo/test_bp.cpp
bp_top/test/tb/bp_top_trace_demo/test_bp.v
bp_top/test/tb/bp_top_trace_demo/testbench.v
bp_top/test/tb/bp_top_trace_demo/wrapper.v

Fixing the multicore testbench. There are multiple fixes to the toplevel network connections, a bug
fixed in the lce_data_cmd and lce_cmd where the coordinates were being incorrectly set, and a bug
where the CCE/LCE ids were being set at the top level. Also added output buffer fifos to the lce
*cmd modules to fix dropped messages in the case of network congestion

Fixing toplevel multicore testbenches

---

bp_be/src/include/bp_be_internal_if_defines.vh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
bp_be/src/v/bp_be_checker/bp_be_checker_top.v
bp_be/src/v/bp_be_checker/bp_be_detector.v
bp_be/src/v/bp_be_checker/bp_be_director.v
bp_be/src/v/bp_be_mem/bp_be_dtlb/bp_be_dtlb.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v
bp_be/src/v/bp_be_top.v
bp_be/src/v/common/bsg_fifo_1r1w_fence.v
bp_fe/src/v/bp_fe_pc_gen.v
bp_fe/src/v/bp_fe_top.v
bp_top/src/v/bp_core.v
bp_top/syn/flist.vcs
bp_top/syn/flist.verilator

This PR is intended to implement the pc_gen rework found at https://docs.google.com/document/d/1r18F7dxunUaRZTh07pzaYvLyV6VwMBJ5X5v9o_PvHIo/edit
It is not functional at the moment (hence the WIP DO NOT MERGE). Use it to give feedback and collaborate.

PC gen rework

---

bp_top/src/v/bp_tile.v

This change uses the bsg_wormhole_router_generalized module in the LCE-CCE Data Command and Response networks within the bp_tile. Routing is StrictYX, route Y first. This allows N & S ports to send messages to E & W, in addition to P, since the LCEs and CCEs acting as sources are connected to N & S.
This change also includes a bug fix to stub the LCE Data Response link_i connection at x=1 on the Proc port, which was previously left floating. This is required because the CCE only connects to the router at x=0. The lce_req_link_i_stitch[1][P] and lce_resp_link_i_stitch[1][P] are also stubbed to 0. Previously the ready_and_rev wire of these signals were tied to the CCE ready_lo signals, but the CCE does not exist at x=1, so the links should be fully stubbed.
regress.v and regress_beebs.v …

Use generalized wormhole router in LCE-CCE Data networks

---

bp_top/src/v/bp_clint.v
bp_top/src/v/bp_core_complex.v
bp_top/src/v/bp_tile.v
bp_top/src/v/bp_top.v

regress.v passes,  currently running regress_beebs.v and atomic queue demos

move wormhole conversion for CCE-MEM interface into bp_tile and bp_clint

---

bp_be/src/include/bp_be_mem_defines.vh
bp_be/src/include/bp_be_rv64_defines.vh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
bp_be/src/v/bp_be_checker/bp_be_scheduler.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v

Adding immediate extension for CSR cmds. Also fixing pipeline to flush on illegal CSR instructions.  Simplifying flush logic a bit

CSR cmd and response fixes

---

bp_top/src/v/bp_mmio_enclave.v

Fixed writing to mtime on reads
Fixed msip core address decode
Fixed using the same w_en signal for per-hart registers

Fixes to MMIO CSR address decoding

---

bp_be/src/v/bp_be_mem/bp_be_csr.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v
bp_be/src/v/bp_be_mem/bp_be_ptw.v
bp_common/src/include/bp_common_csr_defines.vh

Enabled SUM & MXR bits in mstatus
Fixed the global interrupt enable for higher privileges
sepc & stval sign-extension

CSR related fixes

---

bp_be/src/v/bp_be_checker/bp_be_checker_top.v
bp_be/src/v/bp_be_checker/bp_be_director.v
bp_be/src/v/bp_be_checker/bp_be_scheduler.v
bp_be/src/v/bp_be_mem/bp_be_csr.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v
bp_be/src/v/bp_be_top.v
bp_common/src/include/bp_common_csr_defines.vh
bp_top/src/v/bp_core.v
bp_top/src/v/bp_tile.v

Fixed the latching of physical interrupt lines
Fixed CSR read/write masks
Fixed interrupt delegation condition
Interrupts have higher priority than sync exceptions

Fixing interrupt behaviour

---

bp_common/src/include/bp_common_aviary_defines.vh
bp_common/src/include/bp_common_aviary_pkg.vh
bp_me/src/v/wormhole/bp_me_addr_to_cce_id.v
bp_me/src/v/wormhole/bp_me_cce_id_to_cord.v
bp_me/src/v/wormhole/bp_me_cord_to_id.v
bp_me/src/v/wormhole/bp_me_lce_id_to_cord.v
bp_top/src/v/bp_accelerator_complex.v
bp_top/src/v/bp_accelerator_example.v
bp_top/src/v/bp_core_complex.v

This change brings back in the streaming accelerator complex skeleton so that we can add that next.
The BPAI branch is currently broken for single core runs, so I cannot test this, hence WIP

[WIP] Adding streaming accelerator complex skeleton

---

bp_be/src/include/bp_be_internal_if_defines.vh
bp_be/src/v/bp_be_checker/bp_be_checker_top.v
bp_be/src/v/bp_be_checker/bp_be_director.v
bp_be/src/v/bp_be_mem/bp_be_csr.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v
bp_be/src/v/bp_be_top.v
bp_common/syn/Makefile.verilator

Just simplifying things a bit, no functional changes.

Moving fence signals into trap packet

---

docs/software_guide.md

Added Checkpointing and Cosimulation instructions in the software development guide.

Added Dromajo section in Software Guide

---

bp_top/syn/Makefile
bp_top/syn/baseline_regress.lst

Adding a regression list target as well as a baseline list file.

UW ee477 pparrot wi20 regression list

---

bp_common/syn/Makefile.verilator
bp_top/test/common/bp_nonsynth_nbf_loader.v

Small changes to Verilator flow and nonsynth nbf loader.
No RTL changes.

Fixed checkpointing and cosim for Verilator

---

docs/interface_specification.md

This updates the LCE-CCE IF portion of the interface spec to represent the LCE-CCE IF refactor that is on dev. The refactor has not been merged to uw_ee477 branch, though.

update interface spec for new LCE-CCE interface

---

bp_be/test/common/bp_be_nonsynth_calc_tracer.v
bp_be/test/common/bp_be_nonsynth_dcache_tracer.v
bp_be/test/common/bp_be_nonsynth_npc_tracer.v
bp_be/test/common/bp_be_nonsynth_vm_tracer.v
bp_common/syn/Makefile.verilator
bp_me/test/common/bp_cce_nonsynth_tracer.v
bp_top/test/common/bp_nonsynth_commit_tracer.v

This is hopefully the last fix to the file initialization of tracers

Adding fix to tracers for verilator compilation

---

bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache_lce_cmd.v
bp_be/src/v/bp_be_mem/bp_be_mem_top.v
bp_common/src/include/bp_common_cfg_link_pkg.vh
bp_common/test/Makefile
bp_common/test/cfg/cosim.cfg
bp_fe/src/v/bp_fe_lce_cmd.v
bp_me/src/v/cce/bp_uce.v
bp_me/test/common/bp_mem.v
bp_me/test/common/bp_mem_nonsynth_tracer.v
bp_me/test/common/bp_mem_transducer.v
bp_top/src/v/bp_cfg.v
bp_top/src/v/bp_cfg_buffered.v
bp_top/src/v/bp_core_complex.v
bp_top/src/v/bp_io_complex.v
bp_top/src/v/bp_io_tile.v
bp_top/src/v/bp_io_tile_node.v
bp_top/src/v/bp_processor.v
bp_top/src/v/bp_tile.v
bp_top/src/v/bp_tile_node.v
bp_top/test/common/bp_nonsynth_host.v
bp_top/test/tb/bp_processor/testbench.v
bp_top/test/tb/bp_processor/wrapper.v
bp_top/test/tb/bp_softcore/testbench.v

- Fixing x-pessimism in LCE
- Adding host did port to processor
- Changing bp_mem and bp_host to be helpful (less plumbing in testbenches)

Minor updates learned from tapeout

---

bp_top/test/common/bp_nonsynth_commit_tracer.v
bp_top/test/common/bp_nonsynth_cosim.v
bp_top/test/common/dromajo_cosim.cpp
bp_top/test/tb/bp_processor/testbench.v
bp_top/test/tb/bp_softcore/testbench.v

Call the cosim $finish from Verilog

---

Dockerfile
README.md
docker-compose.yml

Wayne is currently testing this for me.

Add instructions for build on docker

---

bp_top/src/v/bp_clint_slice.v

The command should be decoded from the FIFO output.

Fixed CLINT cmd decoding

---

bp_top/src/v/bp_softcore.v

There may be multiple simultaneous returning requests to bp softcore from clint, cfg, cache or I/O.  To handle this conservatively, this PR inserts fifos on the response path as well.  It's also possible to fix this by masking the yumis to these devices, but this is a more timing path friendly approach.  If there ends up being a performance issue, we can bypass the fifos.  If there ends up being an area issue, we can reevaluate.
Fixes #475

Fixing softcore resp arbitration

---

bp_be/src/v/bp_be_mem/bp_be_csr.v

Updating ISA string for M

---

bp_common/syn/Makefile.verilator

replace |& operator with 2>&1 | for greater compatibility

---

bp_be/syn/flist.vcs
bp_common/src/include/bp_common_aviary_pkg.vh
bp_top/src/v/bp_multicore.v
bp_top/src/v/bp_unicore.v
bp_top/syn/Makefile
bp_top/syn/flist.vcs
bp_top/test/tb/bp_tethered/wrapper.v
ci/check_design.sh
ci/example_job.sh
ci/lint.sh
ci/single_core_testlist.sh
docs/getting_started.md
docs/platform_guide.md

Moving away from assuming the usecase of single core == FPGA

Changing softcore to unicore and processor to multicore

---

bp_top/test/common/bp_nonsynth_branch_profiler.v

Fixing block and nonblocking statements

---

bp_common/syn/Makefile.vcs
bp_common/syn/Makefile.verilator

Updating makefiles to play nicer with waveform viewers

---

bp_be/src/v/bp_be_mem/bp_be_csr.v
bp_common/test/Makefile.tests
bp_top/test/tb/bp_tethered/Makefile.testlist

Added a ton more riscv-dv tests and updated them to use M-mode.  This uncovered several problems in dromajo https://github.com/bsg-external/dromajo/pull/3 and several potential bugs in BP. There are ~40/150 failing randomly generated tests.  Most likely the same bug appears multiple times, but nothing like a good 🐛 🔍 !
Upstream riscv-dv is working on a python-based generator, which we should move to instead of the UVM, so that open-source users can use this as well.

[WIP] Better riscv-dv integration

---

bp_be/test/common/bp_be_nonsynth_vm_tracer.v
bp_common/src/v/bp_tlb.v
bp_fe/src/v/bp_fe_icache.v
bp_fe/src/v/bp_fe_mem.v
bp_top/test/common/bp_nonsynth_cache_tracer.v
bp_top/test/tb/bp_tethered/testbench.v

- Adding I$ and ITLB bypass logic -- for consecutive reads, gate the memory read access
- Adding counters for bypass efficacy

Update FE dev

---

bp_top/test/common/bp_nonsynth_cosim.v
bp_top/test/common/dromajo_cosim.cpp
bp_top/test/tb/bp_tethered/testbench.v

Fixed Multicore Cosim Stat Dumping

---

bp_top/test/common/bp_nonsynth_cosim.v
bp_top/test/common/dromajo_cosim.cpp
bp_top/test/tb/bp_tethered/testbench.v

- Fixes for multicore cosim dumping

Update dev to sw_dev

---

bp_be/src/include/bp_be_dcache_tag_info.vh
bp_be/src/v/bp_be_checker/bp_be_director.v
bp_be/src/v/bp_be_mem/bp_be_csr.v
bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
bp_common/src/include/bp_common_aviary_defines.vh
bp_common/src/include/bp_common_aviary_pkg.vh
bp_common/src/include/bp_common_cache_service_if.vh
bp_common/src/include/bp_common_lce_cce_if.vh
bp_common/src/include/bp_common_mem_if.vh
bp_common/src/include/bp_common_pkg.vh
bp_fe/src/include/bp_fe_icache.vh
bp_fe/src/include/bp_fe_icache_pkg.vh
bp_me/src/asm/include/bp_cce_inst.h
bp_me/src/asm/include/bp_common_me_if.h
bp_me/src/include/v/bp_cce_inst.vh
bp_me/src/v/cache/bp_me_cce_to_cache_dma.v

- Adds a parameter to switch between booting in debug mode or directly in M
- Adds a parameter to configure the start PC
Fixes #585

Making bootrom / debug mode optional

---

README.md

Update README to include ICS talk

---

bp_be/src/v/bp_be_calculator/bp_be_instr_decoder.v
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.v
bp_be/src/v/bp_be_mem/bp_be_csr.v
bp_be/src/v/bp_be_mem/bp_be_dcache/bp_be_dcache.v
bp_common/src/include/bp_common_aviary_pkg.vh
bp_common/src/include/bp_common_csr_defines.vh
bp_me/src/include/v/bp_me_pkg.vh
bp_me/src/v/cce/bp_cce_fsm.v
bp_top/src/v/bp_clint_slice.v
bp_top/test/common/bp_nonsynth_cosim.v
bp_top/test/common/bp_nonsynth_host.v
bp_top/test/tb/bp_tethered/testbench.v

- fixing parameter error making L1s "not coherent" in multicore
- fixing sign extensions for tvecs
- FSM CCE invalidation routine fix
- Adding dromajo exception checking in addition to interrupt checking

Various fixes for Linux cosim

---

bp_be/src/include/bp_be_internal_if_defines.vh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.v
bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.v
bp_be/src/v/bp_be_checker/bp_be_director.v
bp_be/src/v/bp_be_top.v

Just a clarity change, separating out branch information from dependency information

Adding branch packet for npc calculation

---

.gitlab-ci.yml
bp_common/software/py/nbf.py
ci/checkpoint.sh

This PR - 
1. Fixes the bootrom flow for checkpointing
2. Adds a new CI target to check checkpointing flow

Fix Bootrom flow with Checkpointing

---

bp_me/src/v/cache/bp_me_cache_dma_to_cce.v
bp_me/test/common/bp_mem.v

Fixes up ASIC flow by
- Removing initialization statement
- Setting sensible defaults in bp_mem

Fixing initialization statement and defaults for bp_mem

---

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_common/src/include/bp_common_aviary_pkg.sv

This PR adds support for a tiny D$. 
(Opening on fe_dev since the required changes for the UCE and the makefiles are already merged into this branch)

Supporting a direct-mapped D$

---

.gitlab-ci.yml
Makefile.common
bp_common/syn/Makefile.verilator
bp_common/syn/Makefile.vivado
bp_common/syn/tcl/vivado_synth.tcl
bp_top/src/v/bp_cacc_vdp.sv
bp_top/src/v/bp_sacc_vdp.sv
bp_top/syn/Makefile
bp_top/test/common/bp_nonsynth_host.sv
bp_top/test/common/bp_nonsynth_nbf_loader.sv
bp_top/test/tb/bp_tethered/Makefile.dc
bp_top/test/tb/bp_tethered/Makefile.vivado
bp_top/test/tb/bp_tethered/design.xdc
bp_top/test/tb/bp_tethered/testbench.sv
ci/synth_vivado.sh

- decreases number of verilator build threads
- adds multiple stdout streams #697 
- Adding done signal to nbf loader
- Adds vivado synthesis flow (#691 )
Waiting on #691

Updating dev to sw_dev

---

bp_common/test/src/perch/vdp.c
bp_common/test/src/perch/vdp.h
bp_top/src/v/bp_cfg.sv

This PR adds support for reading the domain and sac registers in the CFG module.

Adding domain and sac register read in cfg

---

bp_top/test/tb/bp_tethered/Makefile.testlist
docs/getting_started.md
docs/software_guide.md

Updated sections related to cosimulation. Added sim_sample and run_psample target examples.

Updating docs related to cosimulation

---

.gitlab-ci.yml
docs/getting_started.md

Updating dependency list

---

bp_be/src/v/bp_be_calculator/bp_be_csr.sv
bp_top/test/common/bp_nonsynth_cosim.sv
bp_top/test/common/dromajo_cosim.cpp
bp_top/test/tb/bp_tethered/testbench.sv
docs/getting_started.md

Datapath implementation is suboptimal but will get improved with upcoming CSR updates

Adding mstatus checking to dromajo

---

bp_be/src/include/bp_be_defines.svh
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
bp_common/src/include/bp_common_core_if.svh
bp_common/src/v/bp_mmu.sv
bp_common/src/v/bp_tlb.sv
bp_fe/src/v/bp_fe_top.sv
bp_top/test/common/bp_nonsynth_vm_tracer.sv
bp_top/test/tb/bp_tethered/testbench.sv

depends on #737 (for a _slightly_ smaller diff ;))

Adding gigapage support to TLBs

---

bp_be/src/v/bp_be_calculator/bp_be_csr.sv

Illegal instruction read/writing FCSR while ~mstatus.fs

---

bp_be/src/include/bp_be_dcache_pkgdef.svh
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_top/test/common/bp_nonsynth_cosim.sv
bp_top/test/common/dromajo_cosim.cpp
bp_top/test/tb/bp_tethered/Makefile.cfgs
bp_top/test/tb/bp_tethered/Makefile.params
bp_top/test/tb/bp_tethered/Makefile.testlist
bp_top/test/tb/bp_tethered/Makefile.vcs
bp_top/test/tb/bp_tethered/Makefile.verilator
bp_top/test/tb/bp_tethered/testbench.sv

- Adds optional L1 amo op support to D$
- Adds L1 atomic config to aviary

[WIP] Adding amo ops to D$

---

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
bp_common/src/include/bp_common_aviary_defines.svh
bp_common/src/v/bp_mmu.sv
bp_top/test/common/bp_nonsynth_watchdog.sv

Fixes a potential bug of consecutive mode switch, then bypass.
Needs a test before merging @Shashank-Vijay

Switching translation more gracefully in the MMU

---

bp_be/src/v/bp_be_calculator/bp_be_csr.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_common/src/include/bp_common_bedrock_if.svh
bp_common/src/include/bp_common_bedrock_pkgdef.svh
bp_common/src/include/bp_common_cache_engine_if.svh
bp_common/src/include/bp_common_cache_engine_pkgdef.svh
bp_common/src/v/bp_mmu.sv
bp_common/src/v/bp_pma.sv
bp_fe/src/v/bp_fe_icache.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/src/v/lce/bp_lce.sv
bp_me/src/v/lce/bp_lce_req.sv
bp_top/src/v/bp_core.sv
bp_top/src/v/bp_unicore.sv
bp_top/test/common/bp_nonsynth_cache_tracer.sv
docs/interface_specification.md

This PR contains the following:
- Self invalidation in D$ in case of a hit during uncached mode
- UCE changes to support the above
- Removal of uncached mode fault in mmu

Self invalidation in D$ and uncached mode support

---

bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_me/src/v/cache/bp_me_cache_slice.sv
bp_me/src/v/cache/bp_me_cce_to_cache.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/test/common/bp_cce_mmio_cfg_loader.sv
bp_top/test/common/bp_nonsynth_if_verif.sv
bp_top/test/common/bp_nonsynth_nbf_loader.sv
bp_top/test/tb/bp_tethered/Makefile.cfgs

- Optional L2 atomics
- Only supported in UCE + L2 config for now
Depends on #779

Adding L2 atomics

---

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_ctl.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_checker/bp_be_detector.sv
bp_common/src/include/bp_common_cfg_bus_pkgdef.svh
bp_common/src/v/bp_mmu.sv
bp_common/src/v/bp_pma.sv
bp_common/src/v/bsg_mem_1r1w_sync_mask_write_bit_reshape.v
bp_fe/src/include/bp_fe_icache_pkgdef.svh
bp_fe/src/v/bp_fe_bht.sv
bp_fe/src/v/bp_fe_btb.sv
bp_fe/src/v/bp_fe_icache.sv
bp_fe/src/v/bp_fe_pc_gen.sv
bp_fe/src/v/bp_fe_top.sv
bp_fe/test/tb/bp_fe_icache/testbench.sv
bp_fe/test/tb/bp_fe_icache/wrapper.sv
bp_me/src/v/lce/bp_lce_req.sv
bp_top/syn/flist.vcs

- Fixes non-idempotency in I$ #770 
- Adds non-spec mode to I$
- Adds ability to reshape BHT
- Changes faux to 3 cycle latency for critical path

Update dev to fe dev

---

bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_common/src/v/bp_tlb.sv

Depends on https://github.com/bespoke-silicon-group/basejump_stl/pull/418

Make superpage support optional

---

bp_common/src/include/bp_common_addr_pkgdef.svh
bp_common/src/include/bp_common_cache_pkgdef.svh
bp_common/src/include/bp_common_cfg_bus_pkgdef.svh
bp_common/src/include/bp_common_clint_pkgdef.svh
bp_common/src/include/bp_common_host_pkgdef.svh
bp_common/src/include/bp_common_pkg.sv
docs/platform_guide.md

Updates the address map documentation and cleans up some of the address map RTL

Updating address maps

---

bp_top/src/v/bp_unicore.sv
bp_top/src/v/bp_unicore_lite.sv
bp_top/syn/flist.vcs

Update dev to top_dev

---

docs/getting_started.md

Be more specific on Ubuntu prereq 

---

Makefile
bp_me/src/v/cache/bp_me_cce_to_cache.sv
bp_me/test/tb/bp_cce/Makefile.params
bp_me/test/tb/bp_cce/Makefile.testlist
bp_me/test/tb/bp_cce/Makefile.vcs
bp_me/test/tb/bp_cce/Makefile.verilator
bp_me/test/tb/bp_cce/bsg_trace_rom.py
bp_me/test/tb/bp_cce/test_gen.py
bp_me/test/tb/bp_cce/test_memory.py
bp_me/test/tb/bp_cce/testbench.sv
ci/check_design.sh
ci/check_loops.sh

This PR fixes a bug in the the bp_me_cce_to_cache module related to handshaking on the incoming memory command port.
This PR also reworks the ME testbench scripts and fixes some out of date configs in a couple CI scripts.

bugfix in me_cce_to_cache and ME testbench update

---

bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_checker/bp_be_detector.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_be/syn/flist.vcs
bp_be/test/tb/bp_be_dcache/testbench.sv
bp_common/src/v/bsg_dff_reset_half.v
bp_top/syn/flist.vcs
bp_top/test/tb/bp_tethered/testbench.sv

- Delaying D$ cache by a cycle #858 
- Simplify negedge control signal interaction in D$
- Fixing division to zero forwarding bug #859

Update dev to be_dev

---

bp_common/software/py/nbf.py
bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_top/test/common/bp_nonsynth_if_verif.sv
bp_top/test/common/bp_nonsynth_nbf_loader.sv
bp_top/test/tb/bp_tethered/Makefile.cfgs

Tested 33-bit physical address size

Adding 33-bit physical address configs

---

bp_common/src/include/bp_common_aviary_defines.svh
bp_common/src/include/bp_common_bedrock_pkgdef.svh
bp_me/src/include/bp_me_pkg.sv
bp_me/src/include/bp_me_wormhole_defines.svh
bp_me/src/v/cache/bp_me_cce_to_cache.sv
bp_me/src/v/wormhole/bp_me_cord_to_id.sv
bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_cmd.sv
bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_req.sv
bp_me/src/v/wormhole/bp_me_wormhole_packet_encode_lce_resp.sv
bp_top/test/common/bp_nonsynth_nbf_loader.sv
ci/me_regress.sh

This PR is a set of minor changes that were pulled out from the CCE Burst Interface PR as they are minor cleanup items. There are some comments for clarity, a couple lint warning fixes, and minor tweak to the ME CI script to clean bp_me/syn before running.

merge me_dev to dev - comments and lint fixes

---

bp_be/src/include/bp_be_defines.svh
bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
bp_be/syn/flist.vcs
bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_common/src/include/bp_common_defines.svh
bp_fe/syn/flist.vcs
bp_me/syn/flist.vcs
bp_top/syn/flist.vcs

Fixes needed for vivado projects, but also just general QoL

Fix includes and bump submodules

---

bp_common/software/py/nbf.py

This is useful for platforms that don't support reads, like bsg_fpga

Adding validate flag to NBF

---

bp_fe/src/v/bp_fe_bht.sv

Fixing pred idx width

---

docs/interface_specification.md

The meat of this PR clarifies the usage of the forwarded branch prediction data and its relationship to the PC values in the packets, as well as the behavior of attaboy and redirect commands. I have also made some formatting changes (replaced bullets with paragraphs, introduced code formatting) where I thought it would be helpful. Happy to revert portions as desired.

Minor cleanup and expansion of interface docs around frontend branch prediction messages

---

bp_be/syn/flist.vcs
bp_common/src/include/bp_common_aviary_defines.svh
bp_fe/syn/flist.vcs
bp_me/src/v/dev/bp_me_cce_to_cache.sv
bp_me/test/common/bp_ddr.sv
bp_me/test/common/bp_nonsynth_dram.sv
bp_me/test/common/bp_nonsynth_mem.sv
bp_top/src/v/bp_unicore.sv
bp_top/syn/flist.vcs
bp_top/test/tb/bp_tethered/testbench.sv
bp_top/test/tb/bp_tethered/wrapper.sv

#910 , context and justification there
bsg_cache_to_axi, test memory system
Changes to bsg_fpga, width of L2 cache tag RAMs

Fixes L2 hashing problem

---

bp_me/test/tb/bp_cce/Makefile.params
bp_me/test/tb/bp_cce/Makefile.testlist
bp_me/test/tb/bp_cce/bsg_trace_rom.py
bp_me/test/tb/bp_cce/test_memory.py
ci/multicore.sh

This change updates the multicore testing to leverage the newly added aviary ROM features, greatly simplifying the CI script and the multicore testing flow.
Requires SDK including perch at: https://github.com/black-parrot-sdk/perch/commit/781715b754cdad90c9202c0301eb2dc273626ca6
Depends on bp-tests: https://github.com/black-parrot-sdk/bp-tests/pull/15
Addresses #476 in context of multicore tests

update ME multicore testing to leverage aviary ROM

---

bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
bp_top/syn/flist.vcs

This PR bumps dromajo to revert a bad commit.
Fixes failing CI (alongside same bump to dromajo in SDK repo https://github.com/black-parrot-sdk/black-parrot-sdk/pull/22)

bump dromajo to revert bad commit

---

bp_common/syn/v/bsg_mem_1rw_sync_mask_write_bit.v

Adds the hardened swaps for various unicore_L2 memories

Fixing up sv2v hardened memories

---

bp_me/src/v/network/bp_me_axil_client.sv
bp_me/src/v/network/bp_me_axil_master.sv
bp_top/src/v/bp_unicore_axi.sv

The BP unicore AXI wrapper is a generally useful module, so we're adding it here rather than relegating it to zynq-parrot. There are also some various cleanup changes to the axi parameters

Adding unicore axi wrapper to BP

---

bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv

FPGA retiming was broken based on an assumption in HardFloat parameterization. This fix patches BP to work on zynq-parrot and bsg_fpga again by setting the stages parameter correctly in bp_be_pipe_fma. It also relies on a patch to hardfloat

Hotfix for FPGA Retiming

---

.gitlab-ci.yml
bp_be/src/include/bp_be_defines.svh
bp_be/src/v/bp_be_calculator/bp_be_csr.sv
bp_be/src/v/bp_be_checker/bp_be_director.sv
bp_common/software/py/blood_graph.py
bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_common/src/include/bp_common_pkg.sv
bp_common/src/include/bp_common_rv64_pkgdef.svh
bp_me/test/common/bp_ddr.sv
bp_top/test/common/bp_nonsynth_core_profiler.sv
bp_top/test/tb/bp_tethered/testbench.sv
ci/bloodgraph.sh

This PR updates the core stall profiler and adds more distinction between various pipeline dependencies.

Update core profiler

---

.gitmodules
Makefile.tools

This PR clean up `.gitmodules` and `Makefile.tools` to make them uniform and clear.
N/A
tools
Some settings are inconsistent and it causes minor inconveniences.
None.
No impact on functionalities.
Executing `make bleach_all; make tools`
N/A

Cleanup configurations about tools

---

docs/testbench_guide.md

This PR fixes a minor format issue in `docs/testbench_guide.md`.
N/A
docs
The rendering of the document was confusing a bit.
None.
No impact on functionalities.
N/A
N/A

Fix testbench_guide slightly

---

bp_me/src/v/network/bp_me_axil_client.sv
bp_me/src/v/network/bp_me_axil_master.sv
bp_top/src/v/bp_axi_top.sv
bp_top/syn/flist.vcs

Small update for zynq-parrot design

Updates for zynq-parrot and me_dev merge

---

bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_common/src/v/bsg_crossbar_control_locking_o_by_i.v

- Bumps basejump
- Fixes crossbar control bug (#1091 )
- Removes L2 bank suppression for multicore

Various tapeout fixes

---

bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv

The pre-decode logic in the FE queue currently doesn't check whether the issue packet is for an exception or an instruction issue. It just uses the `instr` field of the instruction fetch variant of the fetch/exception union.
This "works" so long as those bits happen to map to zeroes in the exception message; an all-zeroes opcode, reg fields, etc. triggers no hazard conditions nor register reads. The danger is that some in-use bit of the exception payload could put something legitimate in the opcode and pre-decode to an operation which isn't inert.
The effect I've seen is to the hazard detection logic; exceptions can be delayed waiting for arbitrary other instructions due to phantom hazards. It also causes the regfile memories to be read unnecessarily. I haven't traced those signals …

Only pre-decode issue messages, not exceptions

---

bp_be/src/v/bp_be_checker/bp_be_director.sv
bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
bp_common/src/include/bp_common_core_if.svh
bp_common/src/include/bp_common_core_pkgdef.svh
bp_fe/src/v/bp_fe_top.sv
bp_top/test/common/bp_nonsynth_branch_profiler.sv
docs/interface_specification.md

This PR prepares the core FE<->BE interface for #1098. Mostly renaming changes, but also adds the partial instr and message types to support it
None
FE<->BE interface, and everything that touches those
Better to separate out these interface changes so that the functional diff is much smaller and easier to review
None
Potential impact of the change.
Steps to taken to verify the change.
Add any other context about the problem here.
Logs, screenshots or videos that show the issue are very helpful.

Clarification for FE<->BE interface

---

bp_be/src/include/bp_be_ctl_pkgdef.svh
bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache_wbuf.sv
bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
bp_top/syn/flist.vcs
bp_top/test/common/bp_nonsynth_if_verif.sv
bp_top/test/common/dromajo_cosim.cpp

- Support for MULH (#1110)
- Bugfix for wbuf, eliminating class of stalls (#1114)

Update dev to be_bev

---

bp_be/syn/flist.vcs
bp_fe/syn/flist.vcs
bp_me/src/v/cce/bp_cce.sv
bp_me/src/v/cce/bp_cce_fsm.sv
bp_me/src/v/cce/bp_cce_msg.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/src/v/dev/bp_me_cce_to_cache.sv
bp_me/src/v/lce/bp_lce_cmd.sv
bp_me/src/v/network/bp_me_burst_to_stream.sv
bp_me/src/v/network/bp_me_stream_fifo.sv
bp_me/src/v/network/bp_me_stream_pump_control.sv
bp_me/src/v/network/bp_me_stream_pump_in.sv
bp_me/src/v/network/bp_me_stream_pump_out.sv
bp_me/src/v/network/bp_me_stream_wraparound.sv
bp_me/syn/flist.vcs
bp_me/test/tb/bp_cce/testbench.sv
bp_top/syn/flist.vcs
bp_top/test/common/bp_nonsynth_nbf_loader.sv
bp_top/test/tb/bp_tethered/testbench.sv

This PR sets up some cleanup for the stream pumps so that future diffs will be smaller.
None
UCE, CCE and stream pumps
Clarity in preparation for full stream pump refactor
None
Low PPA improvement due to reduced round trip paths along the stream pumps
No functional change, standard regression
Depends on #1119

Stream pump cleanup

---

.gitlab-ci.yml
bp_be/src/include/bp_be_defines.svh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
bp_be/src/v/bp_be_calculator/bp_be_csr.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
bp_be/src/v/bp_be_checker/bp_be_cmd_queue.sv
bp_be/src/v/bp_be_checker/bp_be_detector.sv
bp_be/src/v/bp_be_checker/bp_be_director.sv
bp_be/src/v/bp_be_checker/bp_be_instr_decoder.sv
bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_be/src/v/bp_be_top.sv
bp_common/src/include/bp_common_core_if.svh
bp_common/src/include/bp_common_rv64_csr_defines.svh
bp_common/src/include/bp_common_rv64_pkgdef.svh
bp_fe/src/v/bp_fe_controller.sv
bp_fe/src/v/bp_fe_pc_gen.sv
bp_fe/src/v/bp_fe_realigner.sv
bp_fe/src/v/bp_fe_top.sv
bp_fe/test/common/bp_fe_nonsynth_pc_gen_tracer.sv
bp_top/test/common/bp_nonsynth_core_profiler.sv
bp_top/test/common/bp_nonsynth_nbf_loader.sv
bp_top/test/tb/bp_tethered/testbench.sv
docs/interface_specification.md

This PR refactors the issue and dispatch logic in preparation for compressed instruction support.
None
Backend issue and dispatch logic
There are several extra structs and checks provided for issuing and dispatching instructions. This is important to clarify before C-extension support because otherwise we'll end up reimplementing and fixing bugs / tech debt in the middle of that feature add.
None required, but compressed support is next
We'll have to take a look to make sure no silly paths have snuck in, but there are fewer round trips in this refactor so I don't expect any issues.
Standard regression and linux zynq-parrot run
None

Refactoring issue and dispatch logic in preparation for compressed

---

.gitlab-ci.yml
bp_be/src/include/bp_be_ctl_pkgdef.svh
bp_be/src/include/bp_be_defines.svh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
bp_be/src/v/bp_be_calculator/bp_be_csr.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_checker/bp_be_detector.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_be/src/v/bp_be_top.sv
bp_fe/src/v/bp_fe_icache.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/src/v/lce/bp_lce_req.sv
bp_top/src/v/bp_unicore.sv
bp_top/test/common/bp_nonsynth_core_profiler.sv

Various timing improvements, found from repeated synthesis. Fixes are mostly contained to I$/D$.

Timing Improvements 

---

bp_be/src/include/bp_be_pkg.sv
bp_be/src/v/bp_be_calculator/bp_be_nan_unbox.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_aux.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_fma.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv

see #1161 for context
Waiting for fixes in: https://github.com/black-parrot-sdk/bp-tests/pull/35
to merge
Adding @farzamgl and @mysoreanoop as co-authors

Fixing spec FPU bugs

---

.gitlab-ci.yml
bp_be/src/v/bp_be_calculator/bp_be_csr.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_fe/src/v/bp_fe_icache.sv
bp_me/src/v/cce/bp_cce.sv
bp_me/src/v/cce/bp_cce_fsm.sv
bp_me/src/v/cce/bp_cce_msg.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/src/v/dev/bp_me_cce_to_cache.sv
bp_me/src/v/dev/bp_me_loopback.sv
bp_me/src/v/lce/bp_lce_cmd.sv
bp_me/src/v/lce/bp_lce_req.sv
bp_me/src/v/network/bp_me_stream_pump_out.sv
bp_top/test/tb/bp_tethered/testbench.sv

This PR includes a bulk of fixes required to execute programs on OpenPiton. Namely, it smooths out some edge cases about executing uncached LR/SC and uncached atomics. 
Outstanding ParrotPiton Integration
Caches/Cache Engines
Updates to BYOC repo
No PPA impact

Fixes for OpenPiton Integration

---

.gitlab-ci.yml
bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
bp_common/src/include/bp_common_aviary_pkgdef.svh
bp_fe/src/include/bp_fe_defines.svh
bp_fe/src/v/bp_fe_pc_gen.sv
bp_fe/src/v/bp_fe_ras.sv
bp_top/test/common/bp_nonsynth_if_verif.sv
ci/weird_config.sh

This PR adds a parameterizable return address stack. 
Supersedes #722 
FE
Return address stacks are essential in 
None
Negligible Caremark impact for performance, but return address hits go from 50-98%
Standard regression and cycle-accurate performance monitoring
None

Parameterized RAS

---

bp_be/src/include/bp_be_ctl_pkgdef.svh
bp_be/src/include/bp_be_defines.svh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_long.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
bp_be/src/v/bp_be_checker/bp_be_detector.sv
bp_be/src/v/bp_be_checker/bp_be_director.sv
bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_be/src/v/bp_be_top.sv
bp_common/src/include/bp_common_aviary_cfg_pkgdef.svh
bp_common/src/v/bsg_serial_in_parallel_out_passthrough_dynamic.v
bp_common/syn/Makefile.vcs
bp_fe/src/include/bp_fe_pc_gen_pkgdef.svh
bp_fe/src/v/bp_fe_controller.sv
bp_fe/src/v/bp_fe_icache.sv
bp_fe/src/v/bp_fe_instr_scan.sv
bp_fe/src/v/bp_fe_pc_gen.sv
bp_fe/src/v/bp_fe_realigner.sv
bp_fe/src/v/bp_fe_top.sv
bp_fe/test/tb/bp_fe_icache/wrapper.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/src/v/dev/bp_me_cache_slice.sv

This PR has fixes for critical frontend and backend paths. No functionality changes

Critical Path Fixes

---

bp_be/src/include/bp_be_ctl_pkgdef.svh
bp_be/src/include/bp_be_dcache_pkgdef.svh
bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
bp_be/src/v/bp_be_calculator/bp_be_pipe_mem.sv
bp_be/src/v/bp_be_calculator/bp_be_ptw.sv
bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache_decoder.sv
bp_be/src/v/bp_be_top.sv
bp_be/test/common/bp_be_nonsynth_dcache_tracer.sv
bp_be/test/tb/bp_be_dcache/wrapper.sv
bp_common/src/include/bp_common_cache_engine_pkgdef.svh
bp_common/src/v/bp_mmu.sv
bp_me/src/v/cce/bp_uce.sv
bp_me/src/v/lce/bp_lce.sv
bp_me/src/v/lce/bp_lce_cmd.sv
bp_me/src/v/lce/bp_lce_req.sv
bp_top/src/v/bp_cacc_vdp.sv

This PR refactors the D$ to more reliably handle PTW. This will allow for speculative PTW in the future
None
D$
The current methodology has many gotchas in the pipeline, while this interface is much cleaner
None
No PPA change
Linux boot

D$ Refactor

---

bp_be/src/v/bp_be_calculator/bp_be_csr.sv

minstret CSR needs to be incremented on instruction commit.

minstret hotfix

---

bp_common/syn/Makefile.vcs
bp_common/syn/Makefile.verilator
bp_top/test/common/bp_nonsynth_cosim.sv

Fixes Makefile.vcs and Makefile.verilator so linting actually works.

Fix Makefiles for linting

---

bp_be/src/v/bp_be_calculator/bp_be_calculator_top.sv
bp_be/src/v/bp_be_checker/bp_be_detector.sv
bp_be/src/v/bp_be_checker/bp_be_director.sv
bp_be/src/v/bp_be_checker/bp_be_issue_queue.sv
bp_be/src/v/bp_be_checker/bp_be_scheduler.sv
bp_be/src/v/bp_be_dcache/bp_be_dcache.sv
bp_common/src/include/bp_common_cfg_bus_pkgdef.svh
bp_common/src/include/bp_common_rv64_pkgdef.svh
bp_common/src/v/bp_mmu.sv
bp_fe/src/v/bp_fe_bht.sv
bp_fe/src/v/bp_fe_btb.sv
bp_fe/src/v/bp_fe_controller.sv
bp_fe/src/v/bp_fe_icache.sv
bp_fe/src/v/bp_fe_pc_gen.sv
bp_fe/src/v/bp_fe_realigner.sv
bp_fe/src/v/bp_fe_top.sv
bp_fe/test/common/bp_fe_nonsynth_icache_tracer.sv
bp_top/test/tb/bp_tethered/Makefile.testlist
bp_top/test/tb/bp_tethered/testbench.sv

HOTFIX: This PR fixes a number of issues resulting in inconsistent linux boot
- Bypass logic in I$
- Interrupts waking the processor from a fence.i wait
- Interrupts interrupting PTW
It also introduces several clarity changes to the FE, in preparation for a future refactor

Sanitize FE

---

bp_fe/src/v/bp_fe_icache.sv

Closes https://github.com/black-parrot/black-parrot/issues/1230

Fix case label mismatch
